// Generated by greensum.pagedraw.json
import React from "react";
import "./about_us.css";

export default class About_us extends React.Component {
	render() {
		return (
			<div className="about_us-about_us-00">
				<div className="about_us-0">
					<div className="about_us-home-0">Home</div>
					<div className="about_us-shop-0">Shop</div>
					<div className="about_us-about-0">About </div>
					<div className="about_us-contact-0">Contact</div>
					<div className="about_us-recipes-0">recipes</div>
					<div className="about_us-0-5">
						<div className="about_us-0-5-0">
							<div className="about_us-vector-000">
								<div className="about_us-0-5-0-0-0">
									<div className="about_us-vector-00">
										<div className="about_us-0-5-0-0-0-0-0">
											<div className="about_us-vector-0" />
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div className="about_us-_9">+91 - 9876 54321</div>
					<div className="about_us-0-7">
						<div className="about_us-0-7-0">
							<div className="about_us-vector-00000">
								<div className="about_us-0-7-0-0-0">
									<div className="about_us-vector-0000" />
								</div>
							</div>
						</div>
					</div>
					<div className="about_us-search-0">Search</div>
					<div className="about_us-0-9">
						<div className="about_us-0-9-0">
							<div className="about_us-vector-000001" />
						</div>
					</div>
					<div className="about_us-account-0">Account</div>
					<div className="about_us-cart_0">{"Cart (0)"}</div>
				</div>
				<div className="about_us-1">
					<div className="about_us-rectangle_5" />
				</div>
				<div className="about_us-2">
					<div className="about_us-rectangle_3">
						<div className="about_us-2-0-0">
							<div className="about_us-about_us-0">About us</div>
							<div className="about_us-home_about-0">Home/ About</div>
						</div>
					</div>
				</div>
				<div className="about_us-3">
					<div className="about_us-3-0">
						<div className="about_us-3-0-0">
							<div className="about_us-3-0-0-0">
								<div className="about_us-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_sed_do_eiusmod_tempor_incididunt_ut_labore_et_dolore_magna_aliqua_ut_enim_ad_minim_veniam_quis_nostrud_exercitation_ullamco_laboris_nisi_ut_aliquip_ex_ea_commodo_consequat_duis_aute_irure_dolor_in_reprehenderit_in_voluptate_velit_esse_cillum_dolore_eu_fugiat_nulla_pariatur_excepteur_sint_occaecat_cupidatat_non_proident_sunt_in_culpa_qui_officia_deserunt_mollit_anim_id_est_laborum_-0">
									<div>
										Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
										et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
										aliquip ex ea commodo consequat.
									</div>
									<br />
									<div>
										Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
										pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit
										anim id est laborum.
									</div>
								</div>
								<div className="about_us-rectangle_8">
									<div className="about_us-3-0-0-0-1-0">
										<div className="about_us-vector-000004" />
									</div>
								</div>
								<div className="about_us-our_goals-0">Our Goals</div>
								<div className="about_us-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_-0">
									Lorem ipsum dolor sit amet, consectetur adipiscing elit.
								</div>
								<div className="about_us-vector-000000" />
								<div className="about_us-vector-0000006" />
								<div className="about_us-vector-000003" />
								<div className="about_us-vector-0000000" />
								<div className="about_us-vector-0000040" />
								<div className="about_us-vector-0000015" />
								<div className="about_us-vector-0000014" />
							</div>
						</div>
					</div>
				</div>
				<div className="about_us-4">
					<div className="about_us-ellipse_1" />
					<div className="about_us-ellipse_8" />
					<div className="about_us-ellipse_9" />
				</div>
				<div className="about_us-5">
					<div className="about_us-rectangle_6">
						<div className="about_us-5-0-0">
							<div className="about_us-5-0-0-0">
								<div className="about_us-5-0-0-0-0">
									<div className="about_us-address-0">Address</div>
								</div>
								<div className="about_us-5-0-0-0-1">
									<div className="about_us-12">123, New Colony , Delhi</div>
								</div>
								<div className="about_us-5-0-0-0-2">
									<div className="about_us-contact-00">Contact</div>
								</div>
								<div className="about_us-5-0-0-0-3">
									<div className="about_us-email_greensum_gmail_com_cell_9">
										<div>{"Email : greensum@gmail.com"}</div>
										<div>{"Cell : +91 - 987654321"}</div>
										<div>{"Fax : greensum.io"}</div>
									</div>
								</div>
							</div>
							<div className="about_us-5-0-0-1">
								<div className="about_us-5-0-0-1-0">
									<img
										src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/80c5/cd9e/9811893e3828c2a729d6f4c088384115"
										className="about_us-image-5"
										alt="about"
									/>
								</div>
							</div>
							<div className="about_us-5-0-0-2">
								<div className="about_us-5-0-0-2-0">
									<div className="about_us-useful_links-0">Useful links</div>
								</div>
								<div className="about_us-5-0-0-2-1">
									<div className="about_us-privacy_policy_terms_and_conditions_orders_and_tracking_return_policy_customer_care-0">
										<div>Privacy Policy</div>
										<div>Terms and Conditions</div>
										<div>Orders and Tracking</div>
										<div>Return Policy</div>
										<div>Customer Care</div>
									</div>
								</div>
								<div className="about_us-5-0-0-2-2">
									<div className="about_us-vector-0000041">
										<div className="about_us-5-0-0-2-2-0-0">
											<div className="about_us-vector-0000001" />
										</div>
									</div>
									<div className="about_us-vector-0000037">
										<div className="about_us-5-0-0-2-2-1-0">
											<div className="about_us-vector-0000017">
												<div className="about_us-5-0-0-2-2-1-0-0-0">
													<div className="about_us-vector-0000038" />
												</div>
											</div>
										</div>
									</div>
									<div className="about_us-vector-0000019">
										<div className="about_us-5-0-0-2-2-2-0">
											<div className="about_us-vector-00000372" />
										</div>
									</div>
									<div className="about_us-vector-0000012">
										<div className="about_us-5-0-0-2-2-3-0">
											<div className="about_us-vector-000002" />
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		);
	}
}
