// Generated by greensum.pagedraw.json
import React from 'react';
import './checkout_2.css';


export default class Checkout_2 extends React.Component {
  render() {
    return (
      <div className="checkout_2-checkout_2">
          <div className="checkout_2-0">
              <div className="checkout_2-home-0">Home</div>
              <div className="checkout_2-shop-0">Shop</div>
              <div className="checkout_2-about-0">About </div>
              <div className="checkout_2-contact-0">Contact</div>
              <div className="checkout_2-recipes-0">recipes</div>
              <div className="checkout_2-0-5">
                  <div className="checkout_2-0-5-0">
                      <div className="checkout_2-vector-000">
                          <div className="checkout_2-0-5-0-0-0">
                              <div className="checkout_2-vector-00">
                                  <div className="checkout_2-0-5-0-0-0-0-0">
                                      <div className="checkout_2-vector-0" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="checkout_2-_9">+91 - 9876 54321</div>
              <div className="checkout_2-0-7">
                  <div className="checkout_2-0-7-0">
                      <div className="checkout_2-vector-00000">
                          <div className="checkout_2-0-7-0-0-0">
                              <div className="checkout_2-vector-0000" /> 
                          </div>
                      </div>
                  </div>
              </div>
              <div className="checkout_2-search-0">Search</div>
              <div className="checkout_2-0-9">
                  <div className="checkout_2-0-9-0">
                      <div className="checkout_2-vector-000003" /> 
                  </div>
              </div>
              <div className="checkout_2-account-0">Account</div>
              <div className="checkout_2-cart_1">{"Cart (1)"}</div>
          </div>
          <div className="checkout_2-1">
              <div className="checkout_2-rectangle_5" /> 
          </div>
          <div className="checkout_2-2">
              <div className="checkout_2-rectangle_3" /> 
          </div>
          <div className="checkout_2-3">
              <div className="checkout_2-your_order_is_processing_-0">
                  Your Order is processing.
              </div>
          </div>
          <div className="checkout_2-4">
              <div className="checkout_2-4-0">
                  <div className="checkout_2-4-0-0">
                      <div className="checkout_2-order_history-0">
                          ORDER HISTORY
                      </div>
                  </div>
                  <div className="checkout_2-4-0-1">
                      <div className="checkout_2-_0">#0519CB87E4C1F274</div>
                  </div>
                  <div className="checkout_2-4-0-2">
                      <div className="checkout_2-4-0-2-0">
                          <div className="checkout_2-4-0-2-0-0">
                              <div className="checkout_2-rectangle_54">
                                  <div className="checkout_2-4-0-2-0-0-0-0">
                                      <div className="checkout_2-jul_1">JUL 12, 2020</div>
                                  </div>
                                  <div className="checkout_2-4-0-2-0-0-0-1">
                                      <div className="checkout_2-order_placed-0">
                                          Order placed
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="checkout_2-4-0-2-0-1">
                              <div className="checkout_2-rectangle_6">
                                  <div className="checkout_2-4-0-2-0-1-0-0">
                                      <div className="checkout_2-jul_14">JUL 14, 2020</div>
                                  </div>
                                  <div className="checkout_2-4-0-2-0-1-0-1">
                                      <div className="checkout_2-out_for_delivery-0">
                                          Out for delivery
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div className="checkout_2-4-0-2-1">
                          <div className="checkout_2-4-0-2-1-0">
                              <div className="checkout_2-4-0-2-1-0-0">
                                  <div className="checkout_2-ellipse_4" /> 
                                  <div className="checkout_2-ellipse_5" /> 
                                  <div className="checkout_2-ellipse_48" /> 
                                  <div className="checkout_2-ellipse_47" /> 
                                  <div className="checkout_2-vector_7" /> 
                              </div>
                          </div>
                      </div>
                      <div className="checkout_2-4-0-2-2">
                          <div className="checkout_2-4-0-2-2-0">
                              <div className="checkout_2-rectangle_59">
                                  <div className="checkout_2-4-0-2-2-0-0-0">
                                      <div className="checkout_2-jul_13">JUL 13, 2020</div>
                                  </div>
                                  <div className="checkout_2-4-0-2-2-0-0-1">
                                      <div className="checkout_2-order_processing-0">
                                          Order processing
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="checkout_2-4-0-2-2-1">
                              <div className="checkout_2-rectangle_61">
                                  <div className="checkout_2-4-0-2-2-1-0-0">
                                      <div className="checkout_2-jul_15">JUL 15, 2020</div>
                                  </div>
                                  <div className="checkout_2-4-0-2-2-1-0-1">
                                      <div className="checkout_2-delivered-0">Delivered</div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="checkout_2-4-1">
                  <div className="checkout_2-4-1-0">
                      <div className="checkout_2-products_ordered-0">
                          PRODUCTS ORDERED
                      </div>
                  </div>
                  <div className="checkout_2-4-1-1">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/0e10/7713/4e1950e514790414ac37ad24570fd1a5" className="checkout_2-image-1" /> 
                      <div className="checkout_2-4-1-1-1">
                          <div className="checkout_2-4-1-1-1-0">
                              <div className="checkout_2-cheese_block-0">
                                  Cheese Block
                              </div>
                          </div>
                          <div className="checkout_2-4-1-1-1-1">
                              <div className="checkout_2-line_5" /> 
                          </div>
                          <div className="checkout_2-4-1-1-1-2">
                              <div className="checkout_2-subtotal-0">Subtotal</div>
                              <div className="checkout_2-_1">{"₹ 150"}</div>
                          </div>
                          <div className="checkout_2-4-1-1-1-3">
                              <div className="checkout_2-shipping-0">Shipping</div>
                              <div className="checkout_2-_0-0">{"₹ 0"}</div>
                          </div>
                          <div className="checkout_2-4-1-1-1-4">
                              <div className="checkout_2-taxes-0">Taxes</div>
                              <div className="checkout_2-_2">{"₹ 20.25"}</div>
                          </div>
                          <div className="checkout_2-4-1-1-1-5">
                              <div className="checkout_2-line_4" /> 
                          </div>
                      </div>
                  </div>
                  <div className="checkout_2-4-1-2">
                      <div className="checkout_2-total-0">Total</div>
                      <div className="checkout_2-_17">{"₹ 170.25"}</div>
                  </div>
                  <div className="checkout_2-4-1-3">
                      <div className="checkout_2-rectangle_62">
                          <div className="checkout_2-4-1-3-0-0">
                              <div className="checkout_2-shipping_address-0">
                                  Shipping address
                              </div>
                          </div>
                          <div className="checkout_2-4-1-3-0-1">
                              <div className="checkout_2-4-1-3-0-1-0">
                                  <div className="checkout_2-4-1-3-0-1-0-0">
                                      <div className="checkout_2-vector-0000035" /> 
                                  </div>
                                  <div className="checkout_2-4-1-3-0-1-0-1">
                                      <div className="checkout_2-vector-000001" /> 
                                  </div>
                                  <div className="checkout_2-4-1-3-0-1-0-2">
                                      <div className="checkout_2-ant-design_phone-outlined-0">
                                          <div className="checkout_2-4-1-3-0-1-0-2-0-0">
                                              <div className="checkout_2-vector-0000015" /> 
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="checkout_2-john_doe_1">
                                  <div>John Doe</div>
                                  <div>123, New Colony , E-39 , Sector 4 , Bandra , Mumbai 410210</div>
                                  <div>+91 - 9876561231</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="checkout_2-5">
              <div className="checkout_2-view_order_history-0">
                  View order history
              </div>
              <div className="checkout_2-5-1">
                  <div className="checkout_2-5-1-0">
                      <div className="checkout_2-vector_4" /> 
                  </div>
              </div>
          </div>
          <div className="checkout_2-6">
              <div className="checkout_2-rectangle_67">
                  <div className="checkout_2-6-0-0">
                      <div className="checkout_2-6-0-0-0">
                          <div className="checkout_2-6-0-0-0-0">
                              <div className="checkout_2-address-0">Address</div>
                          </div>
                          <div className="checkout_2-6-0-0-0-1">
                              <div className="checkout_2-12">
                                  123, New Colony , Delhi
                              </div>
                          </div>
                          <div className="checkout_2-6-0-0-0-2">
                              <div className="checkout_2-contact-00">Contact</div>
                          </div>
                          <div className="checkout_2-6-0-0-0-3">
                              <div className="checkout_2-email_greensum_gmail_com_cell_9">
                                  <div>{"Email : greensum@gmail.com"}</div>
                                  <div>{"Cell : +91 - 987654321"}</div>
                                  <div>{"Fax : greensum.io"}</div>
                              </div>
                          </div>
                      </div>
                      <div className="checkout_2-6-0-0-1">
                          <div className="checkout_2-6-0-0-1-0">
                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/80c5/cd9e/9811893e3828c2a729d6f4c088384115" className="checkout_2-image-9" /> 
                          </div>
                      </div>
                      <div className="checkout_2-6-0-0-2">
                          <div className="checkout_2-6-0-0-2-0">
                              <div className="checkout_2-useful_links-0">
                                  Useful links
                              </div>
                          </div>
                          <div className="checkout_2-6-0-0-2-1">
                              <div className="checkout_2-privacy_policy_terms_and_conditions_orders_and_tracking_return_policy_customer_care-0">
                                  <div>Privacy Policy</div>
                                  <div>Terms and Conditions</div>
                                  <div>Orders and Tracking</div>
                                  <div>Return Policy</div>
                                  <div>Customer Care</div>
                              </div>
                          </div>
                          <div className="checkout_2-6-0-0-2-2">
                              <div className="checkout_2-vector-0000039">
                                  <div className="checkout_2-6-0-0-2-2-0-0">
                                      <div className="checkout_2-vector-000002" /> 
                                  </div>
                              </div>
                              <div className="checkout_2-vector-0000018">
                                  <div className="checkout_2-6-0-0-2-2-1-0">
                                      <div className="checkout_2-vector-00000354">
                                          <div className="checkout_2-6-0-0-2-2-1-0-0-0">
                                              <div className="checkout_2-vector-0000022" /> 
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="checkout_2-vector-0000010">
                                  <div className="checkout_2-6-0-0-2-2-2-0">
                                      <div className="checkout_2-vector-0000025" /> 
                                  </div>
                              </div>
                              <div className="checkout_2-vector-000000">
                                  <div className="checkout_2-6-0-0-2-2-3-0">
                                      <div className="checkout_2-vector-0000037" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
