// Generated by greensum.pagedraw.json
import React from 'react';
import './checkout.css';


export default class Checkout extends React.Component {
  render() {
    return (
      <div className="checkout-checkout-000">
          <div className="checkout-0">
              <div className="checkout-home-0">Home</div>
              <div className="checkout-shop-0">Shop</div>
              <div className="checkout-about-0">About </div>
              <div className="checkout-contact-0">Contact</div>
              <div className="checkout-recipes-0">recipes</div>
              <div className="checkout-0-5">
                  <div className="checkout-0-5-0">
                      <div className="checkout-vector-000">
                          <div className="checkout-0-5-0-0-0">
                              <div className="checkout-vector-00">
                                  <div className="checkout-0-5-0-0-0-0-0">
                                      <div className="checkout-vector-0" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="checkout-_9">+91 - 9876 54321</div>
              <div className="checkout-0-7">
                  <div className="checkout-0-7-0">
                      <div className="checkout-vector-00000">
                          <div className="checkout-0-7-0-0-0">
                              <div className="checkout-vector-0000" /> 
                          </div>
                      </div>
                  </div>
              </div>
              <div className="checkout-search-0">Search</div>
              <div className="checkout-0-9">
                  <div className="checkout-0-9-0">
                      <div className="checkout-vector-000002" /> 
                  </div>
              </div>
              <div className="checkout-account-0">Account</div>
              <div className="checkout-cart_1">{"Cart (1)"}</div>
          </div>
          <div className="checkout-1">
              <div className="checkout-rectangle_5" /> 
          </div>
          <div className="checkout-2">
              <div className="checkout-2-0">
                  <div className="checkout-2-0-0">
                      <div className="checkout-2-0-0-0">
                          <div className="checkout-rectangle_7">
                              <div className="checkout-2-0-0-0-0-0">
                                  <div className="checkout-rectangle_3">
                                      <div className="checkout-2-0-0-0-0-0-0-0">
                                          <div className="checkout-checkout-0">Checkout</div>
                                      </div>
                                  </div>
                              </div>
                              <div className="checkout-2-0-0-0-0-1">
                                  <div className="checkout-path_44">
                                      <div className="checkout-2-0-0-0-0-1-0-0">
                                          <div className="checkout-path_4" /> 
                                      </div>
                                  </div>
                                  <div className="checkout-2-0-0-0-0-1-1">
                                      <div className="checkout-2-0-0-0-0-1-1-0">
                                          <div className="checkout-all_payments_are_secure_-0">
                                              All payments are secure.
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="checkout-rectangle_54">
                              <div className="checkout-2-0-0-0-1-0">
                                  <div className="checkout-2-0-0-0-1-0-0">
                                      <div className="checkout-2-0-0-0-1-0-0-0">
                                          <div className="checkout-2-0-0-0-1-0-0-0-0">
                                              <div className="checkout-rectangle_70">
                                                  <div className="checkout-2-0-0-0-1-0-0-0-0-0-0">
                                                      <div className="checkout-price-0">Price</div>
                                                      <div className="checkout-actions-0">Actions</div>
                                                  </div>
                                              </div>
                                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/0e10/7713/4e1950e514790414ac37ad24570fd1a5" className="checkout-image-2" /> 
                                              <div className="checkout-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_fusce_scelerisque_-0">
                                                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce scelerisque.....
                                              </div>
                                              <div className="checkout-cheese_block-0">Cheese Block</div>
                                              <div className="checkout-_1">{"₹ 150.00"}</div>
                                              <div className="checkout-item_name-0">Item Name</div>
                                              <div className="checkout-remove-0">Remove</div>
                                              <div className="checkout-_2">+20.25</div>
                                              <div className="checkout-vector-000000" /> 
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="checkout-2-0-0-0-1-1">
                                  <div className="checkout-line_4" /> 
                              </div>
                              <div className="checkout-2-0-0-0-1-2">
                                  <div className="checkout-total-0">Total</div>
                                  <div className="checkout-_17">{"₹ 170.25"}</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="checkout-3">
              <div className="checkout-rectangle_73">
                  <div className="checkout-3-0-0">
                      <div className="checkout-3-0-0-0">
                          <div className="checkout-3-0-0-0-0">
                              <div className="checkout-apply_promo_code-0">
                                  Apply Promo Code
                              </div>
                          </div>
                      </div>
                      <div className="checkout-rectangle_72" /> 
                  </div>
              </div>
          </div>
          <div className="checkout-4">
              <div className="checkout-contact_information-0">
                  Contact Information
              </div>
              <div className="checkout-4-1">
                  <div className="checkout-4-1-0">
                      <div className="checkout-payment_method-0">
                          Payment Method
                      </div>
                  </div>
              </div>
          </div>
          <div className="checkout-5">
              <div className="checkout-5-0">
                  <div className="checkout-5-0-0">
                      <div className="checkout-rectangle_38">
                          <div className="checkout-5-0-0-0-0">
                              <div className="checkout-email_or_phone_number-0">
                                  Email or phone number
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="checkout-5-0-1">
                      <div className="checkout-shipping_address-0">
                          Shipping Address
                      </div>
                  </div>
              </div>
              <div className="checkout-5-1">
                  <div className="checkout-5-1-0">
                      <div className="checkout-rectangle_74-0">
                          <div className="checkout-5-1-0-0-0">
                              <div className="checkout-5-1-0-0-0-0">
                                  <div className="checkout-5-1-0-0-0-0-0">
                                      <div className="checkout-5-1-0-0-0-0-0-0">
                                          <div className="checkout-rectangle_74">
                                              <div className="checkout-5-1-0-0-0-0-0-0-0-0">
                                                  <div className="checkout-5-1-0-0-0-0-0-0-0-0-0">
                                                      <div className="checkout-5-1-0-0-0-0-0-0-0-0-0-0">
                                                          <div className="checkout-rectangle_76" /> 
                                                      </div>
                                                      <div className="checkout-5-1-0-0-0-0-0-0-0-0-0-1">
                                                          <div className="checkout-rectangle_77" /> 
                                                      </div>
                                                  </div>
                                                  <div className="checkout-rectangle_78" /> 
                                              </div>
                                          </div>
                                          <div className="checkout-rectangle_75" /> 
                                      </div>
                                  </div>
                              </div>
                              <div className="checkout-5-1-0-0-0-1">
                                  <div className="checkout-5-1-0-0-0-1-0">
                                      <div className="checkout-debit_card-0">Debit Card</div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="checkout-6">
              <div className="checkout-6-0">
                  <div className="checkout-6-0-0">
                      <div className="checkout-rectangle_4">
                          <div className="checkout-6-0-0-0-0">
                              <div className="checkout-first_name-0">First name</div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="checkout-6-1">
                  <div className="checkout-6-1-0">
                      <div className="checkout-rectangle_46">
                          <div className="checkout-6-1-0-0-0">
                              <div className="checkout-last_name-0">Last name</div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="checkout-rectangle_75-00">
                  <div className="checkout-6-2-0">
                      <div className="checkout-6-2-0-0">
                          <div className="checkout-6-2-0-0-0">
                              <div className="checkout-6-2-0-0-0-0">
                                  <div className="checkout-rectangle_74-00">
                                      <div className="checkout-6-2-0-0-0-0-0-0">
                                          <div className="checkout-6-2-0-0-0-0-0-0-0">
                                              <div className="checkout-6-2-0-0-0-0-0-0-0-0">
                                                  <div className="checkout-rectangle_76-0" /> 
                                              </div>
                                              <div className="checkout-6-2-0-0-0-0-0-0-0-1">
                                                  <div className="checkout-rectangle_77-0" /> 
                                              </div>
                                          </div>
                                          <div className="checkout-rectangle_78-0" /> 
                                      </div>
                                  </div>
                                  <div className="checkout-rectangle_75-0" /> 
                              </div>
                          </div>
                      </div>
                      <div className="checkout-6-2-0-1">
                          <div className="checkout-6-2-0-1-0">
                              <div className="checkout-credit_card-0">Credit Card</div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="checkout-7">
              <div className="checkout-7-0">
                  <div className="checkout-7-0-0">
                      <div className="checkout-rectangle_47">
                          <div className="checkout-7-0-0-0-0">
                              <div className="checkout-address-0">Address</div>
                          </div>
                      </div>
                  </div>
                  <div className="checkout-7-0-1">
                      <div className="checkout-rectangle_48">
                          <div className="checkout-7-0-1-0-0">
                              <div className="checkout-apartment_suite_etc_-0">
                                  Apartment, suite etc..
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="checkout-7-1">
                  <div className="checkout-7-1-0">
                      <div className="checkout-rectangle_76-00">
                          <div className="checkout-7-1-0-0-0">
                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/7a28/1643/e800d275b2f9aa2248c5a322274552e6" className="checkout-image-9" /> 
                              <div className="checkout-7-1-0-0-0-1">
                                  <div className="checkout-7-1-0-0-0-1-0">
                                      <div className="checkout-upi_bhim-0">UPI / BHIM</div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="checkout-8">
              <div className="checkout-8-0">
                  <div className="checkout-8-0-0">
                      <div className="checkout-rectangle_49">
                          <div className="checkout-8-0-0-0-0">
                              <div className="checkout-city-0">City</div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="checkout-rectangle_77-00">
                  <div className="checkout-8-1-0">
                      <div className="checkout-vector-0000026">
                          <div className="checkout-8-1-0-0-0">
                              <div className="checkout-vector-0000025" /> 
                          </div>
                      </div>
                      <div className="checkout-8-1-0-1">
                          <div className="checkout-8-1-0-1-0">
                              <div className="checkout-wallet-0">Wallet</div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="checkout-9">
              <div className="checkout-rectangle_54-0">
                  <div className="checkout-9-0-0">
                      <div className="checkout-region-0">Region</div>
                  </div>
              </div>
              <div className="checkout-rectangle_53">
                  <div className="checkout-9-1-0">
                      <div className="checkout-state-0">State</div>
                  </div>
              </div>
              <div className="checkout-rectangle_52">
                  <div className="checkout-9-2-0">
                      <div className="checkout-pin_code-0">Pin code</div>
                  </div>
              </div>
          </div>
          <div className="checkout-10">
              <div className="checkout-10-0">
                  <div className="checkout-10-0-0">
                      <div className="checkout-vector_6" /> 
                  </div>
              </div>
              <div className="checkout-rectangle_79">
                  <div className="checkout-10-1-0">
                      <div className="checkout-10-1-0-0">
                          <div className="checkout-place_order-0">Place Order</div>
                          <div className="checkout-checkout-00">Checkout</div>
                      </div>
                  </div>
              </div>
              <div className="checkout-10-2">
                  <div className="checkout-10-2-0">
                      <div className="checkout-vector_5" /> 
                  </div>
              </div>
          </div>
          <div className="checkout-11">
              <div className="checkout-rectangle_6">
                  <div className="checkout-11-0-0">
                      <div className="checkout-11-0-0-0">
                          <div className="checkout-11-0-0-0-0">
                              <div className="checkout-address-00">Address</div>
                          </div>
                          <div className="checkout-11-0-0-0-1">
                              <div className="checkout-12">123, New Colony , Delhi</div>
                          </div>
                          <div className="checkout-11-0-0-0-2">
                              <div className="checkout-contact-00">Contact</div>
                          </div>
                          <div className="checkout-11-0-0-0-3">
                              <div className="checkout-email_greensum_gmail_com_cell_9">
                                  <div>{"Email : greensum@gmail.com"}</div>
                                  <div>{"Cell : +91 - 987654321"}</div>
                                  <div>{"Fax : greensum.io"}</div>
                              </div>
                          </div>
                      </div>
                      <div className="checkout-11-0-0-1">
                          <div className="checkout-11-0-0-1-0">
                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/80c5/cd9e/9811893e3828c2a729d6f4c088384115" className="checkout-image-7" /> 
                          </div>
                      </div>
                      <div className="checkout-11-0-0-2">
                          <div className="checkout-11-0-0-2-0">
                              <div className="checkout-useful_links-0">Useful links</div>
                          </div>
                          <div className="checkout-11-0-0-2-1">
                              <div className="checkout-privacy_policy_terms_and_conditions_orders_and_tracking_return_policy_customer_care-0">
                                  <div>Privacy Policy</div>
                                  <div>Terms and Conditions</div>
                                  <div>Orders and Tracking</div>
                                  <div>Return Policy</div>
                                  <div>Customer Care</div>
                              </div>
                          </div>
                          <div className="checkout-11-0-0-2-2">
                              <div className="checkout-vector-0000007">
                                  <div className="checkout-11-0-0-2-2-0-0">
                                      <div className="checkout-vector-000001" /> 
                                  </div>
                              </div>
                              <div className="checkout-vector-0000011">
                                  <div className="checkout-11-0-0-2-2-1-0">
                                      <div className="checkout-vector-0000000">
                                          <div className="checkout-11-0-0-2-2-1-0-0-0">
                                              <div className="checkout-vector-00000258" /> 
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="checkout-vector-0000019">
                                  <div className="checkout-11-0-0-2-2-2-0">
                                      <div className="checkout-vector-0000002" /> 
                                  </div>
                              </div>
                              <div className="checkout-vector-000003">
                                  <div className="checkout-11-0-0-2-2-3-0">
                                      <div className="checkout-vector-0000004" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
