// Generated by greensum.pagedraw.json
import React from 'react';
import './contact_us.css';


export default class Contact_us extends React.Component {
  render() {
    return (
      <div className="contact_us-contact_us-0">
          <div className="contact_us-0">
              <div className="contact_us-home-0">Home</div>
              <div className="contact_us-shop-0">Shop</div>
              <div className="contact_us-about-0">About </div>
              <div className="contact_us-contact-0">Contact</div>
              <div className="contact_us-recipes-0">Recipes</div>
              <div className="contact_us-0-5">
                  <div className="contact_us-0-5-0">
                      <div className="contact_us-vector-000">
                          <div className="contact_us-0-5-0-0-0">
                              <div className="contact_us-vector-00">
                                  <div className="contact_us-0-5-0-0-0-0-0">
                                      <div className="contact_us-vector-0" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="contact_us-_9">+91 - 9876 54321</div>
              <div className="contact_us-0-7">
                  <div className="contact_us-0-7-0">
                      <div className="contact_us-vector-00000">
                          <div className="contact_us-0-7-0-0-0">
                              <div className="contact_us-vector-0000" /> 
                          </div>
                      </div>
                  </div>
              </div>
              <div className="contact_us-search-0">Search</div>
              <div className="contact_us-0-9">
                  <div className="contact_us-0-9-0">
                      <div className="contact_us-vector-000001" /> 
                  </div>
              </div>
              <div className="contact_us-account-0">Account</div>
              <div className="contact_us-cart_0">{"Cart (0)"}</div>
          </div>
          <div className="contact_us-1">
              <div className="contact_us-rectangle_5" /> 
          </div>
          <div className="contact_us-2">
              <div className="contact_us-2-0">
                  <div className="contact_us-2-0-0">
                      <div className="contact_us-2-0-0-0">
                          <div className="contact_us-rectangle_54">
                              <div className="contact_us-2-0-0-0-0-0">
                                  <div className="contact_us-2-0-0-0-0-0-0">
                                      <div className="contact_us-2-0-0-0-0-0-0-0">
                                          <div className="contact_us-2-0-0-0-0-0-0-0-0">
                                              <div className="contact_us-we_d_love_to_hear_it_from_you_-0">
                                                  <div>{"We’d love to hear it from "}</div>
                                                  <div>you.</div>
                                              </div>
                                              <div className="contact_us-vector-000002" /> 
                                          </div>
                                      </div>
                                  </div>
                                  <div className="contact_us-2-0-0-0-0-0-1">
                                      <div className="contact_us-2-0-0-0-0-0-1-0">
                                          <div className="contact_us-connect_with_us_-0">
                                              {"Connect with us :"}
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="contact_us-2-0-0-0-0-1">
                                  <div className="contact_us-2-0-0-0-0-1-0">
                                      <div className="contact_us-2-0-0-0-0-1-0-0">
                                          <div className="contact_us-name-0">Name</div>
                                      </div>
                                      <div className="contact_us-2-0-0-0-0-1-0-1">
                                          <div className="contact_us-rectangle_3" /> 
                                      </div>
                                  </div>
                                  <div className="contact_us-2-0-0-0-0-1-1">
                                      <div className="contact_us-2-0-0-0-0-1-1-0">
                                          <div className="contact_us-for_support_or_any_questions_email_us_at_abcd_gmail_com-0">
                                              <div>For support or any questions,</div>
                                              <div>{"email us at : abcd@gmail.com"}</div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="contact_us-2-0-0-0-0-2">
                                  <div className="contact_us-2-0-0-0-0-2-0">
                                      <div className="contact_us-2-0-0-0-0-2-0-0">
                                          <div className="contact_us-email-0">Email </div>
                                      </div>
                                  </div>
                                  <div className="contact_us-call_us_-0">{"Call us:"}</div>
                              </div>
                              <div className="contact_us-2-0-0-0-0-3">
                                  <div className="contact_us-rectangle_38" /> 
                                  <div className="contact_us-2-0-0-0-0-3-1">
                                      <div className="contact_us-2-0-0-0-0-3-1-0">
                                          <div className="contact_us-_91">+91 - 987654321</div>
                                      </div>
                                  </div>
                              </div>
                              <div className="contact_us-2-0-0-0-0-4">
                                  <div className="contact_us-2-0-0-0-0-4-0">
                                      <div className="contact_us-2-0-0-0-0-4-0-0">
                                          <div className="contact_us-message-0">Message</div>
                                      </div>
                                  </div>
                                  <div className="contact_us-2-0-0-0-0-4-1">
                                      <div className="contact_us-2-0-0-0-0-4-1-0">
                                          <div className="contact_us-18">1800-1234-3261</div>
                                      </div>
                                  </div>
                              </div>
                              <div className="contact_us-2-0-0-0-0-5">
                                  <div className="contact_us-rectangle_8" /> 
                                  <div className="contact_us-2-0-0-0-0-5-1">
                                      <div className="contact_us-2-0-0-0-0-5-1-0">
                                          <div className="contact_us-landmark_-0">{"Landmark:"}</div>
                                      </div>
                                      <div className="contact_us-2-0-0-0-0-5-1-1">
                                          <div className="contact_us-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_fusce_scelerisque_-0">
                                              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce scelerisque.
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="contact_us-2-0-0-0-0-6">
                                  <div className="contact_us-2-0-0-0-0-6-0">
                                      <div className="contact_us-2-0-0-0-0-6-0-0">
                                          <div className="contact_us-2-0-0-0-0-6-0-0-0">
                                              <div className="contact_us-submit-0">Submit</div>
                                              <div className="contact_us-rectangle_2" /> 
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="contact_us-rectangle_30">
                              <div className="contact_us-2-0-0-0-1-0">
                                  <div className="contact_us-get_in_touch-0">
                                      Get in touch
                                  </div>
                                  <div className="contact_us-home_contact-0">
                                      Home/ Contact
                                  </div>
                              </div>
                          </div>
                          <div className="contact_us-vector-000000" /> 
                          <div className="contact_us-vector-0000008" /> 
                          <div className="contact_us-vector-00000084" /> 
                          <div className="contact_us-vector-0000014" /> 
                          <div className="contact_us-vector-0000009" /> 
                          <div className="contact_us-vector-0000002" /> 
                          <div className="contact_us-vector-00000145" /> 
                          <div className="contact_us-vector-0000012" /> 
                          <div className="contact_us-vector-000003" /> 
                          <div className="contact_us-vector-0000013" /> 
                          <div className="contact_us-vector-0000029" /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="contact_us-3">
              <div className="contact_us-rectangle_6">
                  <div className="contact_us-3-0-0">
                      <div className="contact_us-3-0-0-0">
                          <div className="contact_us-3-0-0-0-0">
                              <div className="contact_us-address-0">Address</div>
                          </div>
                          <div className="contact_us-3-0-0-0-1">
                              <div className="contact_us-12">
                                  123, New Colony , Delhi
                              </div>
                          </div>
                          <div className="contact_us-3-0-0-0-2">
                              <div className="contact_us-contact-00">Contact</div>
                          </div>
                          <div className="contact_us-3-0-0-0-3">
                              <div className="contact_us-email_greensum_gmail_com_cell_9">
                                  <div>{"Email : greensum@gmail.com"}</div>
                                  <div>{"Cell : +91 - 987654321"}</div>
                                  <div>{"Fax : greensum.io"}</div>
                              </div>
                          </div>
                      </div>
                      <div className="contact_us-3-0-0-1">
                          <div className="contact_us-3-0-0-1-0">
                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/80c5/cd9e/9811893e3828c2a729d6f4c088384115" className="contact_us-image-4" /> 
                          </div>
                      </div>
                      <div className="contact_us-3-0-0-2">
                          <div className="contact_us-3-0-0-2-0">
                              <div className="contact_us-useful_links-0">
                                  Useful links
                              </div>
                          </div>
                          <div className="contact_us-3-0-0-2-1">
                              <div className="contact_us-privacy_policy_terms_and_conditions_orders_and_tracking_return_policy_customer_care-0">
                                  <div>Privacy Policy</div>
                                  <div>Terms and Conditions</div>
                                  <div>Orders and Tracking</div>
                                  <div>Return Policy</div>
                                  <div>Customer Care</div>
                              </div>
                          </div>
                          <div className="contact_us-3-0-0-2-2">
                              <div className="contact_us-vector-00000025">
                                  <div className="contact_us-3-0-0-2-2-0-0">
                                      <div className="contact_us-vector-0000000" /> 
                                  </div>
                              </div>
                              <div className="contact_us-vector-00000000">
                                  <div className="contact_us-3-0-0-2-2-1-0">
                                      <div className="contact_us-vector-0000028">
                                          <div className="contact_us-3-0-0-2-2-1-0-0-0">
                                              <div className="contact_us-vector-0000032" /> 
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="contact_us-vector-0000039">
                                  <div className="contact_us-3-0-0-2-2-2-0">
                                      <div className="contact_us-vector-0000006" /> 
                                  </div>
                              </div>
                              <div className="contact_us-vector-00000392">
                                  <div className="contact_us-3-0-0-2-2-3-0">
                                      <div className="contact_us-vector-00000138" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
