// Generated by greensum.pagedraw.json
import React from 'react';
import './landing_page.css';


export default class Landing_page extends React.Component {
  render() {
    return (
      <div className="landing_page-landing_page-0">
          <div className="landing_page-0">
              <div className="landing_page-0-0">
                  <div className="landing_page-0-0-0">
                      <div className="landing_page-rectangle_54">
                          <div className="landing_page-0-0-0-0-0">
                              <div className="landing_page-0-0-0-0-0-0">
                                  <div className="landing_page-rectangle_5" /> 
                                  <div className="landing_page-search_here-0">
                                              Search here
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="landing_page-0-1">
                  <div className="landing_page-0-1-0">
                      <div className="landing_page-0-1-0-0">
                          <div className="landing_page-vector-0" /> 
                          <div className="landing_page-vector-00" /> 
                          <div className="landing_page-vector-000" /> 
                          <div className="landing_page-vector-0000" /> 
                          <div className="landing_page-vector-00000" /> 
                          <div className="landing_page-vector-000002" /> 
                          <div className="landing_page-vector-000001" /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="landing_page-1">
              <div className="landing_page-featured_products-0">
                  Featured Products
              </div>
          </div>
          <div className="landing_page-2">
              <div className="landing_page-2-0">
                  <div className="landing_page-2-0-0">
                      <div className="landing_page-vector-000000" /> 
                  </div>
                  <div className="landing_page-2-0-1">
                      <div className="landing_page-vector-0000017" /> 
                  </div>
              </div>
              <div className="landing_page-2-1">
                  <div className="landing_page-2-1-0">
                      <div className="landing_page-2-1-0-0">
                          <div className="landing_page-vector-0000027" /> 
                          <div className="landing_page-vector-0000006" /> 
                          <div className="landing_page-vector-0000005" /> 
                          <div className="landing_page-vector-000003" /> 
                          <div className="landing_page-vector-0000019" /> 
                      </div>
                  </div>
              </div>
              <div className="landing_page-2-2">
                  <div className="landing_page-2-2-0">
                      <div className="landing_page-vector-00000061" /> 
                  </div>
              </div>
              <div className="landing_page-2-3">
                  <div className="landing_page-2-3-0">
                      <div className="landing_page-rectangle_3">
                          <div className="landing_page-2-3-0-0-0">
                              <div className="landing_page-vector-00000271" /> 
                          </div>
                      </div>
                  </div>
                  <div className="landing_page-2-3-1">
                      <div className="landing_page-lorem_ipsum-0">
                          Lorem Ipsum
                      </div>
                  </div>
              </div>
              <div className="landing_page-2-4">
                  <div className="landing_page-2-4-0">
                      <div className="landing_page-vector-0000004" /> 
                  </div>
              </div>
              <div className="landing_page-2-5">
                  <div className="landing_page-2-5-0">
                      <div className="landing_page-rectangle_59">
                          <div className="landing_page-2-5-0-0-0">
                              <div className="landing_page-vector-0000022" /> 
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="landing_page-3">
              <div className="landing_page-3-0">
                  <div className="landing_page-3-0-0">
                      <div className="landing_page-_1">{"₹ 123"}</div>
                  </div>
              </div>
              <div className="landing_page-3-1">
                  <div className="landing_page-3-1-0">
                      <div className="landing_page-lorem_ipsum-00">
                          Lorem Ipsum
                      </div>
                  </div>
              </div>
          </div>
          <div className="landing_page-4">
              <div className="landing_page-_12">{"₹ 123"}</div>
          </div>
          <div className="landing_page-5">
              <div className="landing_page-5-0">
                  <div className="landing_page-5-0-0">
                      <div className="landing_page-vector-0000030" /> 
                  </div>
              </div>
              <div className="landing_page-5-1">
                  <div className="landing_page-5-1-0">
                      <div className="landing_page-rectangle_6">
                          <div className="landing_page-5-1-0-0-0">
                              <div className="landing_page-vector-0000009" /> 
                          </div>
                      </div>
                  </div>
                  <div className="landing_page-5-1-1">
                      <div className="landing_page-lorem_ipsum-000">
                          Lorem Ipsum
                      </div>
                  </div>
              </div>
              <div className="landing_page-5-2">
                  <div className="landing_page-5-2-0">
                      <div className="landing_page-vector-0000034" /> 
                  </div>
              </div>
              <div className="landing_page-5-3">
                  <div className="landing_page-5-3-0">
                      <div className="landing_page-rectangle_61">
                          <div className="landing_page-5-3-0-0-0">
                              <div className="landing_page-vector-0000013" /> 
                          </div>
                      </div>
                  </div>
              </div>
              <div className="landing_page-5-4">
                  <div className="landing_page-5-4-0">
                      <div className="landing_page-vector-0000039" /> 
                  </div>
              </div>
          </div>
          <div className="landing_page-6">
              <div className="landing_page-6-0">
                  <div className="landing_page-6-0-0">
                      <div className="landing_page-_123">{"₹ 123"}</div>
                  </div>
              </div>
              <div className="landing_page-6-1">
                  <div className="landing_page-6-1-0">
                      <div className="landing_page-lorem_ipsum-0000">
                          Lorem Ipsum
                      </div>
                  </div>
              </div>
          </div>
          <div className="landing_page-7">
              <div className="landing_page-_123-0">{"₹ 123"}</div>
          </div>
          <div className="landing_page-8">
              <div className="landing_page-8-0">
                  <div className="landing_page-8-0-0">
                      <div className="landing_page-8-0-0-0">
                          <div className="landing_page-1_">1   2   3 .... 10</div>
                          <div className="landing_page-rectangle_4" /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="landing_page-9">
              <div className="landing_page-9-0">
                  <div className="landing_page-9-0-0">
                      <div className="landing_page-9-0-0-0">
                          <div className="landing_page-rectangle_58-0">
                              <div className="landing_page-9-0-0-0-0-0">
                                  <div className="landing_page-9-0-0-0-0-0-0">
                                      <div className="landing_page-9-0-0-0-0-0-0-0">
                                          <div className="landing_page-shop_yogurt-0">
                                              {"Shop > Yogurt"}
                                          </div>
                                      </div>
                                      <div className="landing_page-9-0-0-0-0-0-0-1">
                                          <div className="landing_page-this_month_s_hottest_deal-0">
                                              <div>{"This Month’s"}</div>
                                              <div>Hottest Deal</div>
                                          </div>
                                      </div>
                                      <div className="landing_page-9-0-0-0-0-0-0-2">
                                          <div className="landing_page-9-0-0-0-0-0-0-2-0">
                                              <div className="landing_page-9-0-0-0-0-0-0-2-0-0">
                                                  <div className="landing_page-9-0-0-0-0-0-0-2-0-0-0">
                                                      <div className="landing_page-rectangle_58" /> 
                                                      <div className="landing_page-grab_it-0">Grab it</div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="landing_page-rectangle_55">
                                      <div className="landing_page-9-0-0-0-0-0-1-0">
                                          <div className="landing_page-vector-0000014" /> 
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="landing_page-vector-0000003" /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="landing_page-10">
              <div className="landing_page-10-0">
                  <div className="landing_page-10-0-0">
                      <div className="landing_page-vector-00000222" /> 
                  </div>
              </div>
              <div className="landing_page-10-1">
                  <div className="landing_page-10-1-0">
                      <div className="landing_page-our_services-0">
                          Our Services
                      </div>
                  </div>
              </div>
          </div>
          <div className="landing_page-11">
              <div className="landing_page-11-0">
                  <div className="landing_page-11-0-0">
                      <div className="landing_page-11-0-0-0">
                          <div className="landing_page-rectangle_64">
                              <div className="landing_page-11-0-0-0-0-0">
                                  <div className="landing_page-lorem_ipsum_dolor_sit_amet-0">
                                      <div>Lorem ipsum</div>
                                      <div>dolor sit amet</div>
                                  </div>
                              </div>
                              <div className="landing_page-11-0-0-0-0-1">
                                  <div className="landing_page-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_fusce_scelerisque_-0">
                                      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce scelerisque.
                                  </div>
                              </div>
                          </div>
                          <div className="landing_page-ellipse_1">
                              <div className="landing_page-11-0-0-0-1-0">
                                  <div className="landing_page-vector-0000038" /> 
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="landing_page-11-1">
                  <div className="landing_page-11-1-0">
                      <div className="landing_page-11-1-0-0">
                          <div className="landing_page-rectangle_62">
                              <div className="landing_page-11-1-0-0-0-0">
                                  <div className="landing_page-lorem_ipsum_dolor_sit_amet-00">
                                      <div>Lorem ipsum</div>
                                      <div>dolor sit amet </div>
                                  </div>
                              </div>
                              <div className="landing_page-11-1-0-0-0-1">
                                  <div className="landing_page-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_fusce_scelerisque_-00">
                                      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce scelerisque.
                                  </div>
                              </div>
                          </div>
                          <div className="landing_page-ellipse_14">
                              <div className="landing_page-11-1-0-0-1-0">
                                  <div className="landing_page-11-1-0-0-1-0-0">
                                      <div className="landing_page-vector-0000016" /> 
                                      <div className="landing_page-vector-0000001" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="landing_page-11-2">
                  <div className="landing_page-11-2-0">
                      <div className="landing_page-11-2-0-0">
                          <div className="landing_page-rectangle_63">
                              <div className="landing_page-11-2-0-0-0-0">
                                  <div className="landing_page-lorem_ipsum_dolor_sit_amet-000">
                                      <div>Lorem ipsum</div>
                                      <div>dolor sit amet</div>
                                  </div>
                              </div>
                              <div className="landing_page-11-2-0-0-0-1">
                                  <div className="landing_page-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_fusce_scelerisque_-000">
                                      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce scelerisque.
                                  </div>
                              </div>
                          </div>
                          <div className="landing_page-ellipse_15">
                              <div className="landing_page-11-2-0-0-1-0">
                                  <div className="landing_page-vector-00000012" /> 
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="landing_page-12">
              <div className="landing_page-12-0">
                  <div className="landing_page-12-0-0">
                      <div className="landing_page-12-0-0-0">
                          <div className="landing_page-vector-0000021" /> 
                          <div className="landing_page-vector-00000052" /> 
                          <div className="landing_page-vector-0000029" /> 
                          <div className="landing_page-vector-00000059" /> 
                          <div className="landing_page-vector-0000010" /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="landing_page-13">
              <div className="landing_page-rectangle_30">
                  <div className="landing_page-13-0-0">
                      <div className="landing_page-13-0-0-0">
                          <div className="landing_page-13-0-0-0-0">
                              <div className="landing_page-13-0-0-0-0-0">
                                  <div className="landing_page-never_miss_out_on_any_deal_-0">
                                      Never miss out on any deal !
                                  </div>
                                  <div className="landing_page-rectangle_65" /> 
                                  <div className="landing_page-email-0">        Email</div>
                              </div>
                          </div>
                      </div>
                      <div className="landing_page-13-0-0-1">
                          <div className="landing_page-13-0-0-1-0">
                              <div className="landing_page-ellipse_16">
                                  <div className="landing_page-13-0-0-1-0-0-0">
                                      <div className="landing_page-vector-00000030" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="landing_page-14">
              <div className="landing_page-why_choose_us-0">
                  Why Choose us
              </div>
          </div>
          <div className="landing_page-15">
              <div className="landing_page-15-0">
                  <div className="landing_page-15-0-0">
                      <div className="landing_page-15-0-0-0">
                          <div className="landing_page-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_ut_sit_amet_tincidunt_purus_aliquam_erat_volutpat_nullam_imperdiet_-0">
                              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sit amet tincidunt purus. Aliquam erat volutpat. Nullam imperdiet....
                          </div>
                          <div className="landing_page-_-0">{"\“"}</div>
                      </div>
                  </div>
              </div>
              <div className="landing_page-15-1">
                  <div className="landing_page-15-1-0">
                      <div className="landing_page-15-1-0-0">
                          <div className="landing_page-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_ut_sit_amet_tincidunt_purus_aliquam_erat_volutpat_nullam_imperdiet_-00">
                              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sit amet tincidunt purus. Aliquam erat volutpat. Nullam imperdiet....
                          </div>
                          <div className="landing_page-_-00">{"\“"}</div>
                      </div>
                  </div>
              </div>
              <div className="landing_page-15-2">
                  <div className="landing_page-15-2-0">
                      <div className="landing_page-15-2-0-0">
                          <div className="landing_page-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_ut_sit_amet_tincidunt_purus_aliquam_erat_volutpat_nullam_imperdiet_-000">
                              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sit amet tincidunt purus. Aliquam erat volutpat. Nullam imperdiet....
                          </div>
                          <div className="landing_page-_-000">{"\“"}</div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="landing_page-16">
              <div className="landing_page--john_doe-0">-JOHN DOE</div>
          </div>
          <div className="landing_page-17">
              <div className="landing_page-ellipse_2" /> 
              <div className="landing_page-ellipse_1-0" /> 
              <div className="landing_page-ellipse_3" /> 
          </div>
          <div className="landing_page-18">
              <div className="landing_page-rectangle_67">
                  <div className="landing_page-18-0-0">
                      <div className="landing_page-18-0-0-0">
                          <div className="landing_page-18-0-0-0-0">
                              <div className="landing_page-address-0">Address</div>
                          </div>
                          <div className="landing_page-18-0-0-0-1">
                              <div className="landing_page-123">
                                  123, New Colony , Delhi
                              </div>
                          </div>
                          <div className="landing_page-18-0-0-0-2">
                              <div className="landing_page-contact-0">Contact</div>
                          </div>
                          <div className="landing_page-18-0-0-0-3">
                              <div className="landing_page-email_greensum_gmail_com_cell_9">
                                  <div>{"Email : greensum@gmail.com"}</div>
                                  <div>{"Cell : +91 - 987654321"}</div>
                                  <div>{"Fax : greensum.io"}</div>
                              </div>
                          </div>
                      </div>
                      <div className="landing_page-18-0-0-1">
                          <div className="landing_page-18-0-0-1-0">
                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/80c5/cd9e/9811893e3828c2a729d6f4c088384115" className="landing_page-image-4" /> 
                          </div>
                      </div>
                      <div className="landing_page-18-0-0-2">
                          <div className="landing_page-18-0-0-2-0">
                              <div className="landing_page-useful_links-0">
                                  Useful links
                              </div>
                          </div>
                          <div className="landing_page-18-0-0-2-1">
                              <div className="landing_page-privacy_policy_terms_and_conditions_orders_and_tracking_return_policy_customer_care-0">
                                  <div>Privacy Policy</div>
                                  <div>Terms and Conditions</div>
                                  <div>Orders and Tracking</div>
                                  <div>Return Policy</div>
                                  <div>Customer Care</div>
                              </div>
                          </div>
                          <div className="landing_page-18-0-0-2-2">
                              <div className="landing_page-vector-00000344">
                                  <div className="landing_page-18-0-0-2-2-0-0">
                                      <div className="landing_page-vector-00000384" /> 
                                  </div>
                              </div>
                              <div className="landing_page-vector-00000016">
                                  <div className="landing_page-18-0-0-2-2-1-0">
                                      <div className="landing_page-vector-00000168">
                                          <div className="landing_page-18-0-0-2-2-1-0-0-0">
                                              <div className="landing_page-vector-0000018" /> 
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="landing_page-vector-0000026">
                                  <div className="landing_page-18-0-0-2-2-2-0">
                                      <div className="landing_page-vector-00000225" /> 
                                  </div>
                              </div>
                              <div className="landing_page-vector-0000025">
                                  <div className="landing_page-18-0-0-2-2-3-0">
                                      <div className="landing_page-vector-0000011" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
