// Generated by greensum.pagedraw.json
import React from 'react';
import './login_page.css';


export default class Login_page extends React.Component {
  render() {
    return (
      <div className="login_page-login_page-0">
          <div className="login_page-0">
              <div className="login_page-home-0">Home</div>
              <div className="login_page-shop-0">Shop</div>
              <div className="login_page-about-0">About </div>
              <div className="login_page-contact-0">Contact</div>
              <div className="login_page-recipes-0">recipes</div>
              <div className="login_page-0-5">
                  <div className="login_page-0-5-0">
                      <div className="login_page-vector-000">
                          <div className="login_page-0-5-0-0-0">
                              <div className="login_page-vector-00">
                                  <div className="login_page-0-5-0-0-0-0-0">
                                      <div className="login_page-vector-0" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="login_page-_9">+91 - 9876 54321</div>
              <div className="login_page-0-7">
                  <div className="login_page-0-7-0">
                      <div className="login_page-vector-00000">
                          <div className="login_page-0-7-0-0-0">
                              <div className="login_page-vector-0000" /> 
                          </div>
                      </div>
                  </div>
              </div>
              <div className="login_page-search-0">Search</div>
              <div className="login_page-0-9">
                  <div className="login_page-0-9-0">
                      <div className="login_page-vector-000002" /> 
                  </div>
              </div>
              <div className="login_page-account-0">Account</div>
              <div className="login_page-cart_0">{"Cart (0)"}</div>
          </div>
          <div className="login_page-1">
              <div className="login_page-rectangle_5" /> 
          </div>
          <div className="login_page-2">
              <div className="login_page-rectangle_3">
                  <div className="login_page-2-0-0">
                      <div className="login_page-login-0">Login</div>
                  </div>
              </div>
          </div>
          <div className="login_page-3">
              <div className="login_page-3-0">
                  <div className="login_page-3-0-0">
                      <div className="login_page-3-0-0-0">
                          <div className="login_page-image-4">
                              <div className="login_page-3-0-0-0-0-0">
                                  <div className="login_page-lorem_ipsum-0">Lorem Ipsum</div>
                              </div>
                              <div className="login_page-3-0-0-0-0-1">
                                  <div className="login_page-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_-0">
                                      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                  </div>
                              </div>
                              <div className="login_page-3-0-0-0-0-2">
                                  <div className="login_page-ellipse_1" /> 
                                  <div className="login_page-ellipse_8" /> 
                                  <div className="login_page-ellipse_9" /> 
                              </div>
                          </div>
                          <div className="login_page-rectangle_54">
                              <div className="login_page-3-0-0-0-1-0">
                                  <div className="login_page-welcome_back_d-0">
                                      {"Welcome back :D"}
                                  </div>
                              </div>
                              <div className="login_page-3-0-0-0-1-1">
                                  <div className="login_page-email_or_phone_number-0">
                                      Email or Phone number
                                  </div>
                              </div>
                              <div className="login_page-3-0-0-0-1-2">
                                  <div className="login_page-rectangle_38" /> 
                              </div>
                              <div className="login_page-3-0-0-0-1-3">
                                  <div className="login_page-3-0-0-0-1-3-0">
                                      <div className="login_page-3-0-0-0-1-3-0-0">
                                          <div className="login_page-password-0">Password</div>
                                      </div>
                                  </div>
                                  <div className="login_page-vector-000003">
                                      <div className="login_page-3-0-0-0-1-3-1-0">
                                          <div className="login_page-vector-0000028" /> 
                                      </div>
                                  </div>
                              </div>
                              <div className="login_page-3-0-0-0-1-4">
                                  <div className="login_page-rectangle_38-0" /> 
                              </div>
                              <div className="login_page-3-0-0-0-1-5">
                                  <div className="login_page-3-0-0-0-1-5-0">
                                      <div className="login_page-3-0-0-0-1-5-0-0">
                                          <div className="login_page-vector-0000014">
                                              <div className="login_page-3-0-0-0-1-5-0-0-0-0">
                                                  <div className="login_page-vector-000001" /> 
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="login_page-3-0-0-0-1-5-1">
                                      <div className="login_page-3-0-0-0-1-5-1-0">
                                          <div className="login_page-remember_me-0">
                                              Remember me 
                                          </div>
                                      </div>
                                  </div>
                                  <div className="login_page-3-0-0-0-1-5-2">
                                      <div className="login_page-3-0-0-0-1-5-2-0">
                                          <div className="login_page-forgot_password_-0">
                                              {"Forgot Password ?"}
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="login_page-3-0-0-0-1-6">
                                  <div className="login_page-don_t_have_an_account_-0">
                                      {"Don’t have an account ? "}
                                  </div>
                                  <div className="login_page-sign_up-0">Sign up</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="login_page-4">
              <div className="login_page-rectangle_6">
                  <div className="login_page-4-0-0">
                      <div className="login_page-4-0-0-0">
                          <div className="login_page-4-0-0-0-0">
                              <div className="login_page-address-0">Address</div>
                          </div>
                          <div className="login_page-4-0-0-0-1">
                              <div className="login_page-12">
                                  123, New Colony , Delhi
                              </div>
                          </div>
                          <div className="login_page-4-0-0-0-2">
                              <div className="login_page-contact-00">Contact</div>
                          </div>
                          <div className="login_page-4-0-0-0-3">
                              <div className="login_page-email_greensum_gmail_com_cell_9">
                                  <div>{"Email : greensum@gmail.com"}</div>
                                  <div>{"Cell : +91 - 987654321"}</div>
                                  <div>{"Fax : greensum.io"}</div>
                              </div>
                          </div>
                      </div>
                      <div className="login_page-4-0-0-1">
                          <div className="login_page-4-0-0-1-0">
                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/80c5/cd9e/9811893e3828c2a729d6f4c088384115" className="login_page-image-6" /> 
                          </div>
                      </div>
                      <div className="login_page-4-0-0-2">
                          <div className="login_page-4-0-0-2-0">
                              <div className="login_page-useful_links-0">
                                  Useful links
                              </div>
                          </div>
                          <div className="login_page-4-0-0-2-1">
                              <div className="login_page-privacy_policy_terms_and_conditions_orders_and_tracking_return_policy_customer_care-0">
                                  <div>Privacy Policy</div>
                                  <div>Terms and Conditions</div>
                                  <div>Orders and Tracking</div>
                                  <div>Return Policy</div>
                                  <div>Customer Care</div>
                              </div>
                          </div>
                          <div className="login_page-4-0-0-2-2">
                              <div className="login_page-vector-0000011">
                                  <div className="login_page-4-0-0-2-2-0-0">
                                      <div className="login_page-vector-0000034" /> 
                                  </div>
                              </div>
                              <div className="login_page-vector-00000146">
                                  <div className="login_page-4-0-0-2-2-1-0">
                                      <div className="login_page-vector-0000039">
                                          <div className="login_page-4-0-0-2-2-1-0-0-0">
                                              <div className="login_page-vector-000000" /> 
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="login_page-vector-0000002">
                                  <div className="login_page-4-0-0-2-2-2-0">
                                      <div className="login_page-vector-00000118" /> 
                                  </div>
                              </div>
                              <div className="login_page-vector-00000115">
                                  <div className="login_page-4-0-0-2-2-3-0">
                                      <div className="login_page-vector-0000036" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
