// Generated by greensum.pagedraw.json
import React from 'react';
import './mobile_view_with_side_bar.css';


export default class Mobile_view_with_side_bar extends React.Component {
  render() {
    return (
      <div className="mobile_view_with_side_bar-mobile_view_with_side_bar-0">
          <div className="mobile_view_with_side_bar-0">
              <div className="mobile_view_with_side_bar-rectangle_94">
                  <div className="mobile_view_with_side_bar-0-0-0">
                      <div className="mobile_view_with_side_bar-0-0-0-0">
                          <div className="mobile_view_with_side_bar-0-0-0-0-0">
                              <div className="mobile_view_with_side_bar-0-0-0-0-0-0">
                                  <div className="mobile_view_with_side_bar-rectangle_9">
                                      <div className="mobile_view_with_side_bar-0-0-0-0-0-0-0-0">
                                          <div className="mobile_view_with_side_bar-vector-0" /> 
                                      </div>
                                      <div className="mobile_view_with_side_bar-0-0-0-0-0-0-0-1">
                                          <div className="mobile_view_with_side_bar-vector_8" /> 
                                      </div>
                                      <div className="mobile_view_with_side_bar-0-0-0-0-0-0-0-2">
                                          <div className="mobile_view_with_side_bar-about-0">
                                              About
                                          </div>
                                      </div>
                                  </div>
                                  <div className="mobile_view_with_side_bar-rectangle_8">
                                      <div className="mobile_view_with_side_bar-0-0-0-0-0-0-1-0">
                                          <div className="mobile_view_with_side_bar-0-0-0-0-0-0-1-0-0">
                                              <div className="mobile_view_with_side_bar-be_wholesome_-0">
                                                  Be Wholesome. 
                                              </div>
                                              <div className="mobile_view_with_side_bar-vector-00" /> 
                                              <div className="mobile_view_with_side_bar-vector-000" /> 
                                              <div className="mobile_view_with_side_bar-vector-0000" /> 
                                              <div className="mobile_view_with_side_bar-vector-00000" /> 
                                              <div className="mobile_view_with_side_bar-vector-000001" /> 
                                              <div className="mobile_view_with_side_bar-vector-000003" /> 
                                          </div>
                                      </div>
                                  </div>
                                  <div className="mobile_view_with_side_bar-rectangle_87">
                                      <div className="mobile_view_with_side_bar-0-0-0-0-0-0-2-0">
                                          <div className="mobile_view_with_side_bar-vector-0000015" /> 
                                      </div>
                                  </div>
                                  <div className="mobile_view_with_side_bar-rectangle_3">
                                      <div className="mobile_view_with_side_bar-0-0-0-0-0-0-3-0">
                                          <div className="mobile_view_with_side_bar-vector-000000" /> 
                                      </div>
                                  </div>
                                  <div className="mobile_view_with_side_bar-rectangle_86" /> 
                                  <div className="mobile_view_with_side_bar-search_here-0">
                                              Search here
                                  </div>
                                  <div className="mobile_view_with_side_bar-today_s_deals-0">
                                      {"Today’s Deals"}
                                  </div>
                                  <div className="mobile_view_with_side_bar-sign_in-0">
                                      Sign in
                                  </div>
                                  <div className="mobile_view_with_side_bar-orders-0">
                                      Orders
                                  </div>
                                  <div className="mobile_view_with_side_bar-shop-0">
                                      Shop
                                  </div>
                                  <div className="mobile_view_with_side_bar-home-0">
                                      Home
                                  </div>
                                  <div className="mobile_view_with_side_bar-my_account-0">
                                      My Account
                                  </div>
                                  <div className="mobile_view_with_side_bar-contact-0">
                                      Contact
                                  </div>
                                  <div className="mobile_view_with_side_bar-rectangle_85">
                                      <div className="mobile_view_with_side_bar-0-0-0-0-0-0-13-0">
                                          <div className="mobile_view_with_side_bar-vector-0000032" /> 
                                      </div>
                                  </div>
                                  <div className="mobile_view_with_side_bar-vector-0000008" /> 
                                  <div className="mobile_view_with_side_bar-vector-0000006" /> 
                                  <div className="mobile_view_with_side_bar-vector-0000034" /> 
                                  <div className="mobile_view_with_side_bar-vector_9" /> 
                                  <div className="mobile_view_with_side_bar-vector-000002" /> 
                                  <div className="mobile_view_with_side_bar-vector-0000002" /> 
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="mobile_view_with_side_bar-0-0-1">
                      <div className="mobile_view_with_side_bar-lorem_ipsum-0">
                          Lorem Ipsum
                      </div>
                      <div className="mobile_view_with_side_bar-lorem_ipsum-00">
                          Lorem Ipsum
                      </div>
                  </div>
                  <div className="mobile_view_with_side_bar-0-0-2">
                      <div className="mobile_view_with_side_bar-_1">
                          {"₹ 123"}
                      </div>
                      <div className="mobile_view_with_side_bar-0-0-2-1">
                          <div className="mobile_view_with_side_bar-0-0-2-1-0">
                              <div className="mobile_view_with_side_bar-_12">
                                  {"₹ 123"}
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="mobile_view_with_side_bar-0-0-3">
                      <div className="mobile_view_with_side_bar-rectangle_88">
                          <div className="mobile_view_with_side_bar-0-0-3-0-0">
                              <div className="mobile_view_with_side_bar-vector-0000004" /> 
                          </div>
                      </div>
                      <div className="mobile_view_with_side_bar-rectangle_89">
                          <div className="mobile_view_with_side_bar-0-0-3-1-0">
                              <div className="mobile_view_with_side_bar-vector-00000044" /> 
                          </div>
                      </div>
                  </div>
                  <div className="mobile_view_with_side_bar-0-0-4">
                      <div className="mobile_view_with_side_bar-lorem_ipsum-000">
                          Lorem Ipsum
                      </div>
                      <div className="mobile_view_with_side_bar-lorem_ipsum-0000">
                          Lorem Ipsum
                      </div>
                  </div>
                  <div className="mobile_view_with_side_bar-0-0-5">
                      <div className="mobile_view_with_side_bar-_123">
                          {"₹ 123"}
                      </div>
                      <div className="mobile_view_with_side_bar-0-0-5-1">
                          <div className="mobile_view_with_side_bar-0-0-5-1-0">
                              <div className="mobile_view_with_side_bar-_123-0">
                                  {"₹ 123"}
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="mobile_view_with_side_bar-0-0-6">
                      <div className="mobile_view_with_side_bar-0-0-6-0">
                          <div className="mobile_view_with_side_bar-0-0-6-0-0">
                              <div className="mobile_view_with_side_bar-0-0-6-0-0-0">
                                  <div className="mobile_view_with_side_bar-rectangle_92">
                                      <div className="mobile_view_with_side_bar-0-0-6-0-0-0-0-0">
                                          <div className="mobile_view_with_side_bar-this_month_s_hottest_deal-0">
                                              <div>{"This Month’s"}</div>
                                              <div>Hottest Deal</div>
                                          </div>
                                      </div>
                                      <div className="mobile_view_with_side_bar-0-0-6-0-0-0-0-1">
                                          <div className="mobile_view_with_side_bar-0-0-6-0-0-0-0-1-0">
                                              <div className="mobile_view_with_side_bar-0-0-6-0-0-0-0-1-0-0">
                                                  <div className="mobile_view_with_side_bar-0-0-6-0-0-0-0-1-0-0-0">
                                                      <div className="mobile_view_with_side_bar-lorem_ipsum-00000">
                                                          Lorem Ipsum
                                                      </div>
                                                      <div className="mobile_view_with_side_bar-_123-00">
                                                          {"₹ 123"}
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="mobile_view_with_side_bar-rectangle_90">
                                      <div className="mobile_view_with_side_bar-0-0-6-0-0-0-1-0">
                                          <div className="mobile_view_with_side_bar-vector-000004" /> 
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="mobile_view_with_side_bar-0-0-7">
                      <div className="mobile_view_with_side_bar-rectangle_91">
                          <div className="mobile_view_with_side_bar-0-0-7-0-0">
                              <div className="mobile_view_with_side_bar-vector-00000024" /> 
                              <div className="mobile_view_with_side_bar-0-0-7-0-0-1">
                                  <div className="mobile_view_with_side_bar-0-0-7-0-0-1-0">
                                      <div className="mobile_view_with_side_bar-lorem_ipsum_dolor_sit_amet-0">
                                          Lorem ipsum dolor sit amet 
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="mobile_view_with_side_bar-0-0-7-0-1">
                              <div className="mobile_view_with_side_bar-0-0-7-0-1-0">
                                  <div className="mobile_view_with_side_bar-0-0-7-0-1-0-0">
                                      <div className="mobile_view_with_side_bar-0-0-7-0-1-0-0-0">
                                          <div className="mobile_view_with_side_bar-vector-00000066" /> 
                                          <div className="mobile_view_with_side_bar-vector-00000061" /> 
                                      </div>
                                  </div>
                              </div>
                              <div className="mobile_view_with_side_bar-0-0-7-0-1-1">
                                  <div className="mobile_view_with_side_bar-0-0-7-0-1-1-0">
                                      <div className="mobile_view_with_side_bar-lorem_ipsum_dolor_sit_amet-00">
                                          Lorem ipsum dolor sit amet 
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="mobile_view_with_side_bar-0-0-7-0-2">
                              <div className="mobile_view_with_side_bar-vector-00000326" /> 
                              <div className="mobile_view_with_side_bar-0-0-7-0-2-1">
                                  <div className="mobile_view_with_side_bar-0-0-7-0-2-1-0">
                                      <div className="mobile_view_with_side_bar-lorem_ipsum_dolor_sit_amet-000">
                                          Lorem ipsum dolor sit amet 
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="mobile_view_with_side_bar-0-0-8">
                      <div className="mobile_view_with_side_bar-top-0">Top</div>
                  </div>
                  <div className="mobile_view_with_side_bar-0-0-9">
                      <div className="mobile_view_with_side_bar-rectangle_6">
                          <div className="mobile_view_with_side_bar-0-0-9-0-0">
                              <div className="mobile_view_with_side_bar-0-0-9-0-0-0">
                                  <div className="mobile_view_with_side_bar-0-0-9-0-0-0-0">
                                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/0930/f37e/69a5a9edacfc3874abed26870864d082" className="mobile_view_with_side_bar-image-3" /> 
                                  </div>
                              </div>
                              <div className="mobile_view_with_side_bar-0-0-9-0-0-1">
                                  <div className="mobile_view_with_side_bar-0-0-9-0-0-1-0">
                                      <div className="mobile_view_with_side_bar-privacy_policy_terms_and_conditions_orders_and-0">
                                          <div>Privacy Policy</div>
                                          <div>Terms and Conditions</div>
                                          <div>Orders and </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="mobile_view_with_side_bar-0-0-9-0-0-2">
                                  <div className="mobile_view_with_side_bar-0-0-9-0-0-2-0">
                                      <div className="mobile_view_with_side_bar-tracking_return_policy_customer_care-0">
                                          <div>Tracking</div>
                                          <div>Return Policy</div>
                                          <div>Customer Care</div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
