// Generated by greensum.pagedraw.json
import React from 'react';
import './mobile_view.css';


export default class Mobile_view extends React.Component {
  render() {
    return (
      <div className="mobile_view-mobile_view-0">
          <div className="mobile_view-0">
              <div className="mobile_view-0-0">
                  <div className="mobile_view-0-0-0">
                      <div className="mobile_view-rectangle_8" /> 
                  </div>
                  <div className="mobile_view-0-0-1">
                      <div className="mobile_view-rectangle_82" /> 
                  </div>
                  <div className="mobile_view-0-0-2">
                      <div className="mobile_view-rectangle_83" /> 
                  </div>
              </div>
              <div className="mobile_view-vector-0" /> 
              <div className="mobile_view-0-2">
                  <div className="mobile_view-0-2-0">
                      <div className="mobile_view-vector-00" /> 
                  </div>
                  <div className="mobile_view-0-2-1">
                      <div className="mobile_view-vector-000" /> 
                      <div className="mobile_view-vector-0000" /> 
                  </div>
              </div>
          </div>
          <div className="mobile_view-1">
              <div className="mobile_view-rectangle_85">
                  <div className="mobile_view-1-0-0">
                      <div className="mobile_view-vector-00000" /> 
                  </div>
              </div>
          </div>
          <div className="mobile_view-2">
              <div className="mobile_view-rectangle_87">
                  <div className="mobile_view-2-0-0">
                      <div className="mobile_view-2-0-0-0">
                          <div className="mobile_view-be_wholesome_-0">
                              Be Wholesome. 
                          </div>
                          <div className="mobile_view-vector-000002" /> 
                          <div className="mobile_view-vector-0000021" /> 
                          <div className="mobile_view-vector-000003" /> 
                          <div className="mobile_view-vector-000001" /> 
                          <div className="mobile_view-vector-0000036" /> 
                          <div className="mobile_view-vector-00000362" /> 
                          <div className="mobile_view-vector-0000037" /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="mobile_view-3">
              <div className="mobile_view-rectangle_3">
                  <div className="mobile_view-3-0-0">
                      <div className="mobile_view-vector-0000013" /> 
                  </div>
              </div>
              <div className="mobile_view-rectangle_87-0">
                  <div className="mobile_view-3-1-0">
                      <div className="mobile_view-vector-000000" /> 
                  </div>
              </div>
          </div>
          <div className="mobile_view-4">
              <div className="mobile_view-lorem_ipsum-0">
                  Lorem Ipsum
              </div>
              <div className="mobile_view-lorem_ipsum-00">
                  Lorem Ipsum
              </div>
          </div>
          <div className="mobile_view-5">
              <div className="mobile_view-_1">{"₹ 123"}</div>
              <div className="mobile_view-5-1">
                  <div className="mobile_view-5-1-0">
                      <div className="mobile_view-_12">{"₹ 123"}</div>
                  </div>
              </div>
          </div>
          <div className="mobile_view-6">
              <div className="mobile_view-rectangle_88">
                  <div className="mobile_view-6-0-0">
                      <div className="mobile_view-vector-0000032" /> 
                  </div>
              </div>
              <div className="mobile_view-rectangle_89">
                  <div className="mobile_view-6-1-0">
                      <div className="mobile_view-vector-0000005" /> 
                  </div>
              </div>
          </div>
          <div className="mobile_view-7">
              <div className="mobile_view-lorem_ipsum-000">
                  Lorem Ipsum
              </div>
              <div className="mobile_view-lorem_ipsum-0000">
                  Lorem Ipsum
              </div>
          </div>
          <div className="mobile_view-8">
              <div className="mobile_view-_123">{"₹ 123"}</div>
              <div className="mobile_view-8-1">
                  <div className="mobile_view-8-1-0">
                      <div className="mobile_view-_123-0">{"₹ 123"}</div>
                  </div>
              </div>
          </div>
          <div className="mobile_view-9">
              <div className="mobile_view-9-0">
                  <div className="mobile_view-9-0-0">
                      <div className="mobile_view-9-0-0-0">
                          <div className="mobile_view-rectangle_9">
                              <div className="mobile_view-9-0-0-0-0-0">
                                  <div className="mobile_view-this_month_s_hottest_deal-0">
                                      <div>{"This Month’s"}</div>
                                      <div>Hottest Deal</div>
                                  </div>
                              </div>
                              <div className="mobile_view-9-0-0-0-0-1">
                                  <div className="mobile_view-9-0-0-0-0-1-0">
                                      <div className="mobile_view-9-0-0-0-0-1-0-0">
                                          <div className="mobile_view-9-0-0-0-0-1-0-0-0">
                                              <div className="mobile_view-lorem_ipsum-00000">
                                                  Lorem Ipsum
                                              </div>
                                              <div className="mobile_view-_123-00">{"₹ 123"}</div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="mobile_view-rectangle_90">
                              <div className="mobile_view-9-0-0-0-1-0">
                                  <div className="mobile_view-vector-0000001" /> 
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="mobile_view-10">
              <div className="mobile_view-rectangle_91">
                  <div className="mobile_view-10-0-0">
                      <div className="mobile_view-vector-0000015" /> 
                      <div className="mobile_view-10-0-0-1">
                          <div className="mobile_view-10-0-0-1-0">
                              <div className="mobile_view-lorem_ipsum_dolor_sit_amet-0">
                                  Lorem ipsum dolor sit amet 
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="mobile_view-10-0-1">
                      <div className="mobile_view-10-0-1-0">
                          <div className="mobile_view-10-0-1-0-0">
                              <div className="mobile_view-10-0-1-0-0-0">
                                  <div className="mobile_view-vector-0000024" /> 
                                  <div className="mobile_view-vector-00000052" /> 
                              </div>
                          </div>
                      </div>
                      <div className="mobile_view-10-0-1-1">
                          <div className="mobile_view-10-0-1-1-0">
                              <div className="mobile_view-lorem_ipsum_dolor_sit_amet-00">
                                  Lorem ipsum dolor sit amet 
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="mobile_view-10-0-2">
                      <div className="mobile_view-vector-0000020" /> 
                      <div className="mobile_view-10-0-2-1">
                          <div className="mobile_view-10-0-2-1-0">
                              <div className="mobile_view-lorem_ipsum_dolor_sit_amet-000">
                                  Lorem ipsum dolor sit amet 
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="mobile_view-11">
              <div className="mobile_view-top-0">Top</div>
          </div>
          <div className="mobile_view-12">
              <div className="mobile_view-rectangle_6">
                  <div className="mobile_view-12-0-0">
                      <div className="mobile_view-12-0-0-0">
                          <div className="mobile_view-12-0-0-0-0">
                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/0930/f37e/69a5a9edacfc3874abed26870864d082" className="mobile_view-image-9" /> 
                          </div>
                      </div>
                      <div className="mobile_view-12-0-0-1">
                          <div className="mobile_view-12-0-0-1-0">
                              <div className="mobile_view-privacy_policy_terms_and_conditions_orders-0">
                                  <div>Privacy Policy</div>
                                  <div>Terms and Conditions</div>
                                  <div>Orders  </div>
                              </div>
                          </div>
                      </div>
                      <div className="mobile_view-12-0-0-2">
                          <div className="mobile_view-12-0-0-2-0">
                              <div className="mobile_view-tracking_return_policy_customer_care-0">
                                  <div>Tracking</div>
                                  <div>Return Policy</div>
                                  <div>Customer Care</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
