// Generated by greensum.pagedraw.json
import React from "react";
import "./my_account.css";

export default class My_account extends React.Component {
	render() {
		return (
			<div className="my_account-my_account-00">
				<div className="my_account-0">
					<div className="my_account-home-0">Home</div>
					<div className="my_account-shop-0">Shop</div>
					<div className="my_account-about-0">About </div>
					<div className="my_account-contact-0">Contact</div>
					<div className="my_account-recipes-0">recipes</div>
					<div className="my_account-0-5">
						<div className="my_account-0-5-0">
							<div className="my_account-vector-000">
								<div className="my_account-0-5-0-0-0">
									<div className="my_account-vector-00">
										<div className="my_account-0-5-0-0-0-0-0">
											<div className="my_account-vector-0" />
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div className="my_account-_9">+91 - 9876 54321</div>
					<div className="my_account-0-7">
						<div className="my_account-0-7-0">
							<div className="my_account-vector-00000">
								<div className="my_account-0-7-0-0-0">
									<div className="my_account-vector-0000" />
								</div>
							</div>
						</div>
					</div>
					<div className="my_account-search-0">Search</div>
					<div className="my_account-0-9">
						<div className="my_account-0-9-0">
							<div className="my_account-vector-000002" />
						</div>
					</div>
					<div className="my_account-account-0">Account</div>
					<div className="my_account-cart_0">{"Cart (0)"}</div>
				</div>
				<div className="my_account-1">
					<div className="my_account-rectangle_5" />
				</div>
				<div className="my_account-2">
					<div className="my_account-rectangle_3">
						<div className="my_account-2-0-0">
							<div className="my_account-my_account-0">My Account</div>
						</div>
					</div>
				</div>
				<div className="my_account-3">
					<div className="my_account-3-0">
						<div className="my_account-3-0-0">
							<div className="my_account-vector-000001" />
						</div>
						<div className="my_account-3-0-1">
							<div className="my_account-vector-000004" />
						</div>
					</div>
					<div className="my_account-3-1">
						<div className="my_account-3-1-0">
							<div className="my_account-3-1-0-0">
								<div className="my_account-vector-000000" />
								<div className="my_account-vector-0000000" />
								<div className="my_account-vector-0000018" />
								<div className="my_account-vector-0000016" />
								<div className="my_account-vector-0000042" />
							</div>
						</div>
					</div>
					<div className="my_account-3-2">
						<div className="my_account-3-2-0">
							<img
								src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/8b27/eef1/1e9d351f406b17d1305b4b31bf3fc3d4"
								className="my_account-image-5"
							/>
							<div className="my_account-3-2-0-1">
								<div className="my_account-3-2-0-1-0">
									<div className="my_account-john_doe-0">John Doe</div>
								</div>
							</div>
						</div>
						<div className="my_account-3-2-1">
							<div className="my_account-vector_1" />
						</div>
						<div className="my_account-3-2-2">
							<div className="my_account-my_wallet-0">My wallet</div>
						</div>
						<div className="my_account-3-2-3">
							<div className="my_account-paytm-0">Paytm</div>
							<div className="my_account-3-2-3-1">
								<div className="my_account-3-2-3-1-0">
									<div className="my_account-_1">{"₹ 123"}</div>
								</div>
							</div>
						</div>
						<div className="my_account-3-2-4">
							<div className="my_account-card_1">Card 1</div>
							<div className="my_account-3-2-4-1">
								<div className="my_account-3-2-4-1-0">
									<div className="my_account-xxxx-0">XXXX</div>
								</div>
							</div>
						</div>
						<div className="my_account-3-2-5">
							<div className="my_account-card_2">Card 2</div>
							<div className="my_account-3-2-5-1">
								<div className="my_account-3-2-5-1-0">
									<div className="my_account-xxxx-00">XXXX</div>
								</div>
							</div>
						</div>
						<div className="my_account-3-2-6">
							<div className="my_account-add_a_new_payment_method-0">Add a new payment method</div>
						</div>
						<div className="my_account-3-2-7">
							<div className="my_account-vector_11" />
						</div>
						<div className="my_account-3-2-8">
							<div className="my_account-change_password-0">Change password</div>
						</div>
						<div className="my_account-3-2-9">
							<div className="my_account-close_your_account-0">Close your account</div>
						</div>
					</div>
					<div className="my_account-3-3">
						<div className="my_account-3-3-0">
							<div className="my_account-3-3-0-0">
								<div className="my_account-rectangle_9">
									<div className="my_account-3-3-0-0-0-0">
										<div className="my_account-vector-0000021" />
									</div>
									<div className="my_account-3-3-0-0-0-1">
										<div className="my_account-personal_information-0">Personal information</div>
									</div>
									<div className="my_account-3-3-0-0-0-2">
										<div className="my_account-john_doe-00">John Doe</div>
									</div>
									<div className="my_account-3-3-0-0-0-3">
										<div className="my_account-e-mail_address-0">E-mail Address</div>
									</div>
									<div className="my_account-3-3-0-0-0-4">
										<div className="my_account-johndoe_example_com-0">johndoe@example.com</div>
									</div>
									<div className="my_account-3-3-0-0-0-5">
										<div className="my_account-mobile_number-0">Mobile number</div>
									</div>
									<div className="my_account-3-3-0-0-0-6">
										<div className="my_account-_91">+91 - 987654321</div>
									</div>
									<div className="my_account-3-3-0-0-0-7">
										<div className="my_account-shipping_address-0">Shipping address</div>
									</div>
									<div className="my_account-3-3-0-0-0-8">
										<div className="my_account-30">3088 Nelson Street, Nestor Falls, Ontario 432142</div>
									</div>
									<div className="my_account-3-3-0-0-0-9">
										<div className="my_account-vector-000003" />
									</div>
								</div>
								<div className="my_account-vector-0000014" />
							</div>
						</div>
					</div>
					<div className="my_account-3-4">
						<div className="my_account-3-4-0">
							<div className="my_account-3-4-0-0">
								<div className="my_account-vector-0000024" />
								<div className="my_account-vector-0000020" />
								<div className="my_account-vector-0000023" />
								<div className="my_account-vector-00000009" />
								<div className="my_account-vector-0000017" />
							</div>
						</div>
					</div>
				</div>
				<div className="my_account-4">
					<div className="my_account-rectangle_6">
						<div className="my_account-4-0-0">
							<div className="my_account-4-0-0-0">
								<div className="my_account-4-0-0-0-0">
									<div className="my_account-address-0">Address</div>
								</div>
								<div className="my_account-4-0-0-0-1">
									<div className="my_account-12">123, New Colony , Delhi</div>
								</div>
								<div className="my_account-4-0-0-0-2">
									<div className="my_account-contact-00">Contact</div>
								</div>
								<div className="my_account-4-0-0-0-3">
									<div className="my_account-email_greensum_gmail_com_cell_9">
										<div>{"Email : greensum@gmail.com"}</div>
										<div>{"Cell : +91 - 987654321"}</div>
										<div>{"Fax : greensum.io"}</div>
									</div>
								</div>
							</div>
							<div className="my_account-4-0-0-1">
								<div className="my_account-4-0-0-1-0">
									<img
										src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/80c5/cd9e/9811893e3828c2a729d6f4c088384115"
										className="my_account-image-7"
									/>
								</div>
							</div>
							<div className="my_account-4-0-0-2">
								<div className="my_account-4-0-0-2-0">
									<div className="my_account-useful_links-0">Useful links</div>
								</div>
								<div className="my_account-4-0-0-2-1">
									<div className="my_account-privacy_policy_terms_and_conditions_orders_and_tracking_return_policy_customer_care-0">
										<div>Privacy Policy</div>
										<div>Terms and Conditions</div>
										<div>Orders and Tracking</div>
										<div>Return Policy</div>
										<div>Customer Care</div>
									</div>
								</div>
								<div className="my_account-4-0-0-2-2">
									<div className="my_account-vector-00000172">
										<div className="my_account-4-0-0-2-2-0-0">
											<div className="my_account-vector-0000008" />
										</div>
									</div>
									<div className="my_account-vector-0000025">
										<div className="my_account-4-0-0-2-2-1-0">
											<div className="my_account-vector-0000019">
												<div className="my_account-4-0-0-2-2-1-0-0-0">
													<div className="my_account-vector-00000213" />
												</div>
											</div>
										</div>
									</div>
									<div className="my_account-vector-0000040">
										<div className="my_account-4-0-0-2-2-2-0">
											<div className="my_account-vector-0000028" />
										</div>
									</div>
									<div className="my_account-vector-00000215">
										<div className="my_account-4-0-0-2-2-3-0">
											<div className="my_account-vector-0000006" />
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		);
	}
}
