// Generated by greensum.pagedraw.json
import React from 'react';
import './products.css';


export default class Products extends React.Component {
  render() {
    return (
      <div className="products-products-0">
          <div className="products-0">
              <div className="products-home-0">Home</div>
              <div className="products-shop-0">Shop</div>
              <div className="products-about-0">About </div>
              <div className="products-contact-0">Contact</div>
              <div className="products-recipes-0">recipes</div>
              <div className="products-0-5">
                  <div className="products-0-5-0">
                      <div className="products-vector-000">
                          <div className="products-0-5-0-0-0">
                              <div className="products-vector-00">
                                  <div className="products-0-5-0-0-0-0-0">
                                      <div className="products-vector-0" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="products-_9">+91 - 9876 54321</div>
              <div className="products-0-7">
                  <div className="products-0-7-0">
                      <div className="products-vector-00000">
                          <div className="products-0-7-0-0-0">
                              <div className="products-vector-0000" /> 
                          </div>
                      </div>
                  </div>
              </div>
              <div className="products-search-0">Search</div>
              <div className="products-0-9">
                  <div className="products-0-9-0">
                      <div className="products-vector-000000" /> 
                  </div>
              </div>
              <div className="products-account-0">Account</div>
              <div className="products-cart_0">{"Cart (0)"}</div>
          </div>
          <div className="products-1">
              <div className="products-rectangle_5" /> 
          </div>
          <div className="products-2">
              <div className="products-rectangle_3">
                  <div className="products-2-0-0">
                      <div className="products-our_store-0">Our store</div>
                      <div className="products-home_shop-0">Home/ shop</div>
                  </div>
              </div>
          </div>
          <div className="products-3">
              <div className="products-recently_viewed-0">
                  Recently  viewed
              </div>
          </div>
          <div className="products-4">
              <div className="products-rectangle_31">
                  <div className="products-4-0-0">
                      <div className="products-vector-000001" /> 
                  </div>
                  <div className="products-4-0-1">
                      <div className="products-lorem_ipsum-0">Lorem Ipsum</div>
                  </div>
                  <div className="products-4-0-2">
                      <div className="products-_1">{"₹ 123"}</div>
                  </div>
              </div>
              <div className="products-rectangle_32">
                  <div className="products-4-1-0">
                      <div className="products-vector-0000013" /> 
                  </div>
                  <div className="products-4-1-1">
                      <div className="products-lorem_ipsum-00">Lorem Ipsum</div>
                  </div>
                  <div className="products-4-1-2">
                      <div className="products-_12">{"₹ 123"}</div>
                  </div>
              </div>
          </div>
          <div className="products-5">
              <div className="products-rectangle_34">
                  <div className="products-5-0-0">
                      <div className="products-vector-0000006" /> 
                  </div>
                  <div className="products-5-0-1">
                      <div className="products-lorem_ipsum-000">Lorem Ipsum</div>
                  </div>
                  <div className="products-5-0-2">
                      <div className="products-_123">{"₹ 123"}</div>
                  </div>
              </div>
              <div className="products-rectangle_33">
                  <div className="products-5-1-0">
                      <div className="products-vector-00000139" /> 
                  </div>
                  <div className="products-5-1-1">
                      <div className="products-lorem_ipsum-0000">
                          Lorem Ipsum
                      </div>
                  </div>
                  <div className="products-5-1-2">
                      <div className="products-_123-0">{"₹ 123"}</div>
                  </div>
              </div>
          </div>
          <div className="products-6">
              <div className="products-6-0">
                  <div className="products-6-0-0">
                      <div className="products-all-0">All</div>
                  </div>
              </div>
              <div className="products-6-1">
                  <div className="products-6-1-0">
                      <div className="products-lorem_ipsum-00000">
                          lorem Ipsum
                      </div>
                  </div>
              </div>
              <div className="products-6-2">
                  <div className="products-6-2-0">
                      <div className="products-lorem_ipsum-000004">
                          lorem Ipsum
                      </div>
                  </div>
              </div>
              <div className="products-6-3">
                  <div className="products-6-3-0">
                      <div className="products-lorem_ipsum-000003">
                          lorem Ipsum
                      </div>
                  </div>
              </div>
              <div className="products-6-4">
                  <div className="products-6-4-0">
                      <div className="products-lorem_ipsum-000002">
                          lorem Ipsum
                      </div>
                  </div>
              </div>
              <div className="products-6-5">
                  <div className="products-6-5-0">
                      <div className="products-lorem_ipsum-0000032">
                          lorem Ipsum
                      </div>
                  </div>
              </div>
              <div className="products-6-6">
                  <div className="products-6-6-0">
                      <div className="products-6-6-0-0">
                          <div className="products-rectangle_2">
                              <div className="products-6-6-0-0-0-0">
                                  <div className="products-vector_4" /> 
                              </div>
                          </div>
                          <div className="products-price_low_to_high-0">
                              {"Price : Low to high"}
                          </div>
                      </div>
                  </div>
              </div>
              <div className="products-rectangle_35">
                  <div className="products-6-7-0">
                      <div className="products-vector-000002" /> 
                  </div>
              </div>
              <div className="products-rectangle_36">
                  <div className="products-6-8-0">
                      <div className="products-vector-000003" /> 
                  </div>
              </div>
          </div>
          <div className="products-7">
              <div className="products-rectangle_37">
                  <div className="products-7-0-0">
                      <div className="products-vector-0000023" /> 
                  </div>
                  <div className="products-7-0-1">
                      <div className="products-7-0-1-0">
                          <div className="products-7-0-1-0-0">
                              <div className="products-7-0-1-0-0-0">
                                  <div className="products-lorem_ipsum-0000024">
                                      Lorem Ipsum
                                  </div>
                                  <div className="products-_123-00">{"₹ 123"}</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="products-rectangle_38">
                  <div className="products-7-1-0">
                      <div className="products-vector-0000028" /> 
                  </div>
                  <div className="products-7-1-1">
                      <div className="products-7-1-1-0">
                          <div className="products-7-1-1-0-0">
                              <div className="products-7-1-1-0-0-0">
                                  <div className="products-lorem_ipsum-000001">
                                      Lorem Ipsum
                                  </div>
                                  <div className="products-_123-000">{"₹ 123"}</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="products-rectangle_39">
                  <div className="products-7-2-0">
                      <div className="products-vector-00000289" /> 
                  </div>
                  <div className="products-7-2-1">
                      <div className="products-7-2-1-0">
                          <div className="products-7-2-1-0-0">
                              <div className="products-7-2-1-0-0-0">
                                  <div className="products-lorem_ipsum-0000029">
                                      Lorem Ipsum
                                  </div>
                                  <div className="products-_123-0000">{"₹ 123"}</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="products-rectangle_4">
                  <div className="products-7-3-0">
                      <div className="products-vector-00000063" /> 
                  </div>
                  <div className="products-7-3-1">
                      <div className="products-7-3-1-0">
                          <div className="products-7-3-1-0-0">
                              <div className="products-7-3-1-0-0-0">
                                  <div className="products-lorem_ipsum-000000">
                                      Lorem Ipsum
                                  </div>
                                  <div className="products-_123-00000">{"₹ 123"}</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="products-8">
              <div className="products-rectangle_41">
                  <div className="products-8-0-0">
                      <div className="products-vector-0000026" /> 
                  </div>
                  <div className="products-8-0-1">
                      <div className="products-8-0-1-0">
                          <div className="products-8-0-1-0-0">
                              <div className="products-8-0-1-0-0-0">
                                  <div className="products-lorem_ipsum-0000006">
                                      Lorem Ipsum
                                  </div>
                                  <div className="products-_123-000003">{"₹ 123"}</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="products-rectangle_42">
                  <div className="products-8-1-0">
                      <div className="products-vector-0000009" /> 
                  </div>
                  <div className="products-8-1-1">
                      <div className="products-8-1-1-0">
                          <div className="products-8-1-1-0-0">
                              <div className="products-8-1-1-0-0-0">
                                  <div className="products-lorem_ipsum-0000037">
                                      Lorem Ipsum
                                  </div>
                                  <div className="products-_123-0000032">{"₹ 123"}</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="products-rectangle_43">
                  <div className="products-8-2-0">
                      <div className="products-vector-0000021" /> 
                  </div>
                  <div className="products-8-2-1">
                      <div className="products-8-2-1-0">
                          <div className="products-8-2-1-0-0">
                              <div className="products-8-2-1-0-0-0">
                                  <div className="products-lorem_ipsum-00000291">
                                      Lorem Ipsum
                                  </div>
                                  <div className="products-_123-000000">{"₹ 123"}</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="products-rectangle_44">
                  <div className="products-8-3-0">
                      <div className="products-vector-0000011" /> 
                  </div>
                  <div className="products-8-3-1">
                      <div className="products-8-3-1-0">
                          <div className="products-8-3-1-0-0">
                              <div className="products-8-3-1-0-0-0">
                                  <div className="products-lorem_ipsum-0000019">
                                      Lorem Ipsum
                                  </div>
                                  <div className="products-_123-000002">{"₹ 123"}</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="products-9">
              <div className="products-rectangle_45">
                  <div className="products-9-0-0">
                      <div className="products-vector-0000018" /> 
                  </div>
                  <div className="products-9-0-1">
                      <div className="products-9-0-1-0">
                          <div className="products-9-0-1-0-0">
                              <div className="products-9-0-1-0-0-0">
                                  <div className="products-lorem_ipsum-0000021">
                                      Lorem Ipsum
                                  </div>
                                  <div className="products-_123-00000322">{"₹ 123"}</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="products-rectangle_46">
                  <div className="products-9-1-0">
                      <div className="products-vector-0000008" /> 
                  </div>
                  <div className="products-9-1-1">
                      <div className="products-9-1-1-0">
                          <div className="products-9-1-1-0-0">
                              <div className="products-9-1-1-0-0-0">
                                  <div className="products-lorem_ipsum-0000011">
                                      Lorem Ipsum
                                  </div>
                                  <div className="products-_123-0000026">{"₹ 123"}</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="products-rectangle_47">
                  <div className="products-9-2-0">
                      <div className="products-vector-00000235" /> 
                  </div>
                  <div className="products-9-2-1">
                      <div className="products-9-2-1-0">
                          <div className="products-9-2-1-0-0">
                              <div className="products-9-2-1-0-0-0">
                                  <div className="products-lorem_ipsum-0000033">
                                      Lorem Ipsum
                                  </div>
                                  <div className="products-_123-0000001">{"₹ 123"}</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="products-rectangle_48">
                  <div className="products-9-3-0">
                      <div className="products-vector-0000017" /> 
                  </div>
                  <div className="products-9-3-1">
                      <div className="products-9-3-1-0">
                          <div className="products-9-3-1-0-0">
                              <div className="products-9-3-1-0-0-0">
                                  <div className="products-lorem_ipsum-0000041">
                                      Lorem Ipsum
                                  </div>
                                  <div className="products-_123-000004">{"₹ 123"}</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="products-10">
              <div className="products-10-0">
                  <div className="products-10-0-0">
                      <div className="products-10-0-0-0">
                          <div className="products-1_">1   2   3 .... 10</div>
                          <div className="products-rectangle_49" /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="products-11">
              <div className="products-11-0">
                  <div className="products-11-0-0">
                      <div className="products-image-1">
                          <div className="products-11-0-0-0-0">
                              <div className="products-lorem_ipsum-00000240">
                                  Lorem Ipsum
                              </div>
                          </div>
                          <div className="products-11-0-0-0-1">
                              <div className="products-_123-000001">{"₹ 123"}</div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="products-11-1">
                  <div className="products-11-1-0">
                      <div className="products-related_products-0">
                          Related  Products
                      </div>
                  </div>
                  <div className="products-11-1-1">
                      <div className="products-11-1-1-0">
                          <div className="products-11-1-1-0-0">
                              <div className="products-11-1-1-0-0-0">
                                  <div className="products-image-5">
                                      <div className="products-11-1-1-0-0-0-0-0">
                                          <div className="products-lorem_ipsum-0000035">
                                              Lorem Ipsum
                                          </div>
                                      </div>
                                  </div>
                                  <div className="products-_123-0000023">{"₹ 123"}</div>
                              </div>
                          </div>
                      </div>
                      <div className="products-11-1-1-1">
                          <div className="products-11-1-1-1-0">
                              <div className="products-11-1-1-1-0-0">
                                  <div className="products-11-1-1-1-0-0-0">
                                      <div className="products-11-1-1-1-0-0-0-0">
                                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/3706/c5fa/a53ea0617291a070161f46b67e849b59" className="products-image-4" /> 
                                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/7d01/f3c6/64ed830030ef9978e06dee32887fadc4" className="products-image-2" /> 
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="products-11-1-1-1-1">
                              <div className="products-lorem_ipsum-0000018">
                                  Lorem Ipsum
                              </div>
                              <div className="products-lorem_ipsum-00000417">
                                  Lorem Ipsum
                              </div>
                          </div>
                          <div className="products-11-1-1-1-2">
                              <div className="products-_123-0000002">{"₹ 123"}</div>
                              <div className="products-_123-0000008">{"₹ 123"}</div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="products-12">
              <div className="products-ellipse_1" /> 
              <div className="products-ellipse_8" /> 
              <div className="products-ellipse_9" /> 
          </div>
          <div className="products-13">
              <div className="products-rectangle_6">
                  <div className="products-13-0-0">
                      <div className="products-13-0-0-0">
                          <div className="products-13-0-0-0-0">
                              <div className="products-address-0">Address</div>
                          </div>
                          <div className="products-13-0-0-0-1">
                              <div className="products-123">123, New Colony , Delhi</div>
                          </div>
                          <div className="products-13-0-0-0-2">
                              <div className="products-contact-00">Contact</div>
                          </div>
                          <div className="products-13-0-0-0-3">
                              <div className="products-email_greensum_gmail_com_cell_9">
                                  <div>{"Email : greensum@gmail.com"}</div>
                                  <div>{"Cell : +91 - 987654321"}</div>
                                  <div>{"Fax : greensum.io"}</div>
                              </div>
                          </div>
                      </div>
                      <div className="products-13-0-0-1">
                          <div className="products-13-0-0-1-0">
                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/80c5/cd9e/9811893e3828c2a729d6f4c088384115" className="products-image-0" /> 
                          </div>
                      </div>
                      <div className="products-13-0-0-2">
                          <div className="products-13-0-0-2-0">
                              <div className="products-useful_links-0">Useful links</div>
                          </div>
                          <div className="products-13-0-0-2-1">
                              <div className="products-privacy_policy_terms_and_conditions_orders_and_tracking_return_policy_customer_care-0">
                                  <div>Privacy Policy</div>
                                  <div>Terms and Conditions</div>
                                  <div>Orders and Tracking</div>
                                  <div>Return Policy</div>
                                  <div>Customer Care</div>
                              </div>
                          </div>
                          <div className="products-13-0-0-2-2">
                              <div className="products-vector-0000015">
                                  <div className="products-13-0-0-2-2-0-0">
                                      <div className="products-vector-0000003" /> 
                                  </div>
                              </div>
                              <div className="products-vector-0000032">
                                  <div className="products-13-0-0-2-2-1-0">
                                      <div className="products-vector-0000029">
                                          <div className="products-13-0-0-2-2-1-0-0-0">
                                              <div className="products-vector-0000014" /> 
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="products-vector-0000024">
                                  <div className="products-13-0-0-2-2-2-0">
                                      <div className="products-vector-00000032" /> 
                                  </div>
                              </div>
                              <div className="products-vector-0000020">
                                  <div className="products-13-0-0-2-2-3-0">
                                      <div className="products-vector-00000232" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
