// Generated by greensum.pagedraw.json
import React from 'react';
import './product_card.css';


export default class Product_card extends React.Component {
  render() {
    return (
      <div className="product_card-product_card-0">
          <div className="product_card-0">
              <div className="product_card-home-0">Home</div>
              <div className="product_card-shop-0">Shop</div>
              <div className="product_card-about-0">About </div>
              <div className="product_card-contact-0">Contact</div>
              <div className="product_card-support-0">support</div>
              <div className="product_card-0-5">
                  <div className="product_card-0-5-0">
                      <div className="product_card-vector-000">
                          <div className="product_card-0-5-0-0-0">
                              <div className="product_card-vector-00">
                                  <div className="product_card-0-5-0-0-0-0-0">
                                      <div className="product_card-vector-0" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="product_card-_9">+91 - 9876 54321</div>
              <div className="product_card-0-7">
                  <div className="product_card-0-7-0">
                      <div className="product_card-vector-00000">
                          <div className="product_card-0-7-0-0-0">
                              <div className="product_card-vector-0000" /> 
                          </div>
                      </div>
                  </div>
              </div>
              <div className="product_card-search-0">Search</div>
              <div className="product_card-0-9">
                  <div className="product_card-0-9-0">
                      <div className="product_card-vector-000002" /> 
                  </div>
              </div>
              <div className="product_card-account-0">Account</div>
              <div className="product_card-cart_0">{"Cart (0)"}</div>
          </div>
          <div className="product_card-1">
              <div className="product_card-rectangle_5" /> 
          </div>
          <div className="product_card-2">
              <div className="product_card-rectangle_3">
                  <div className="product_card-2-0-0">
                      <div className="product_card-our_store-0">Our store</div>
                      <div className="product_card-home_shop-0">Home/ shop</div>
                  </div>
              </div>
          </div>
          <div className="product_card-3">
              <div className="product_card-3-0">
                  <div className="product_card-3-0-0">
                      <div className="product_card-vector-0000021" /> 
                  </div>
              </div>
              <div className="product_card-3-1">
                  <div className="product_card-3-1-0">
                      <div className="product_card-3-1-0-0">
                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/2b3c/60c0/30adb074ca23dd99d3328c1eeb1c3824" className="product_card-image-7" /> 
                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/7e04/0286/9fa2149ab91c641542be20e834d414f4" className="product_card-image-2" /> 
                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/3de2/dd04/afb950dcf9105071c82902d8e615de81" className="product_card-image-73" /> 
                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/c79b/1470/0296484e3e6c965b05769ab323bd56b0" className="product_card-image-5" /> 
                      </div>
                  </div>
              </div>
              <div className="product_card-3-2">
                  <div className="product_card-3-2-0">
                      <div className="product_card-vector-000001" /> 
                  </div>
              </div>
              <div className="product_card-3-3">
                  <div className="product_card-3-3-0">
                      <div className="product_card-cheese_block-0">
                          Cheese Block
                      </div>
                  </div>
                  <div className="product_card-3-3-1">
                      <div className="product_card-_4">
                          {"( 4 customer reviews )"}
                      </div>
                  </div>
                  <div className="product_card-3-3-2">
                      <div className="product_card-3-3-2-0">
                          <div className="product_card-3-3-2-0-0">
                              <div className="product_card-3-3-2-0-0-0">
                                  <div className="product_card-15">  150</div>
                                  <div className="product_card-_-0">{"₹"}</div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="product_card-3-3-3">
                      <div className="product_card-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_fusce_scelerisque_libero_eget_pulvinar_vestibulum_nulla_egestas_pellentesque_molestie_fusce_neque_turpis_porttitor_id_metus_et_efficitur_viverra_ligula_-0">
                          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce scelerisque libero eget pulvinar vestibulum. Nulla egestas pellentesque molestie. Fusce neque turpis porttitor id metus et, efficitur viverra ligula.
                      </div>
                  </div>
                  <div className="product_card-3-3-4">
                      <div className="product_card-3-3-4-0">
                          <div className="product_card-3-3-4-0-0">
                              <div className="product_card-1-0">1</div>
                          </div>
                      </div>
                      <div className="product_card-3-3-4-1">
                          <div className="product_card-3-3-4-1-0">
                              <div className="product_card-3-3-4-1-0-0">
                                  <div className="product_card-buy_now-0">Buy now</div>
                                  <div className="product_card-rectangle_3-0" /> 
                              </div>
                          </div>
                      </div>
                      <div className="product_card-3-3-4-2">
                          <div className="product_card-3-3-4-2-0">
                              <div className="product_card-rectangle_9">
                                  <div className="product_card-3-3-4-2-0-0-0">
                                      <div className="product_card-vector-000000" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="product_card-3-3-5">
                      <div className="product_card-3-3-5-0">
                          <div className="product_card-3-3-5-0-0">
                              <div className="product_card-3-3-5-0-0-0">
                                  <div className="product_card-category_lorem_ipsum_dolor_tag_lorem_ipsum_lorem_ipsum_share_-0">
                                      <div>{"Category : Lorem ipsum dolor"}</div>
                                      <div>{"Tag : lorem Ipsum , lorem Ipsum"}</div>
                                      <div>{"Share :"}</div>
                                  </div>
                                  <div className="product_card-ic_baseline-mail-outline-0">
                                      <div className="product_card-3-3-5-0-0-0-1-0">
                                          <div className="product_card-vector-000004" /> 
                                      </div>
                                  </div>
                                  <div className="product_card-ant-design_message-outlined-0">
                                      <div className="product_card-3-3-5-0-0-0-2-0">
                                          <div className="product_card-vector-0000017" /> 
                                      </div>
                                  </div>
                                  <div className="product_card-vector-000003">
                                      <div className="product_card-3-3-5-0-0-0-3-0">
                                          <div className="product_card-vector-0000000" /> 
                                      </div>
                                  </div>
                                  <div className="product_card-ellipse_7">
                                      <div className="product_card-3-3-5-0-0-0-4-0">
                                          <div className="product_card-vector-0000001" /> 
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="product_card-3-4">
                  <div className="product_card-3-4-0">
                      <div className="product_card-vector-0000031" /> 
                  </div>
              </div>
          </div>
          <div className="product_card-4">
              <div className="product_card-description-0">
                  Description
              </div>
              <div className="product_card-additional_information-0">
                  Additional Information
              </div>
              <div className="product_card-reviews_4">
                  {"Reviews (4)"}
              </div>
          </div>
          <div className="product_card-5">
              <div className="product_card-rectangle_1">
                  <div className="product_card-5-0-0">
                      <div className="product_card-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_fusce_scelerisque_libero_eget_pulvinar_vestibulum_nulla_egestas_pellentesque_molestie_fusce_neque_turpis_porttitor_id_metus_et_efficitur_viverra_ligula_donec_fringilla_eget_purus_ut_placerat_nam_pharetra_mauris_non_ornare_semper_-0">
                          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce scelerisque libero eget pulvinar vestibulum. Nulla egestas pellentesque molestie. Fusce neque turpis, porttitor id metus et, efficitur viverra ligula. Donec fringilla eget purus ut placerat. Nam pharetra mauris non ornare semper.
                      </div>
                  </div>
              </div>
          </div>
          <div className="product_card-6">
              <div className="product_card-6-0">
                  <div className="product_card-6-0-0">
                      <div className="product_card-image-78">
                          <div className="product_card-6-0-0-0-0">
                              <div className="product_card-lorem_ipsum-0">
                                  Lorem Ipsum
                              </div>
                          </div>
                          <div className="product_card-6-0-0-0-1">
                              <div className="product_card-_1">{"₹ 123"}</div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="product_card-6-1">
                  <div className="product_card-6-1-0">
                      <div className="product_card-related_products-0">
                          Related  Products
                      </div>
                  </div>
                  <div className="product_card-6-1-1">
                      <div className="product_card-6-1-1-0">
                          <div className="product_card-6-1-1-0-0">
                              <div className="product_card-6-1-1-0-0-0">
                                  <div className="product_card-image-6">
                                      <div className="product_card-6-1-1-0-0-0-0-0">
                                          <div className="product_card-lorem_ipsum-00">
                                              Lorem Ipsum
                                          </div>
                                      </div>
                                  </div>
                                  <div className="product_card-_12">{"₹ 123"}</div>
                              </div>
                          </div>
                      </div>
                      <div className="product_card-6-1-1-1">
                          <div className="product_card-6-1-1-1-0">
                              <div className="product_card-6-1-1-1-0-0">
                                  <div className="product_card-6-1-1-1-0-0-0">
                                      <div className="product_card-6-1-1-1-0-0-0-0">
                                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/3706/c5fa/a53ea0617291a070161f46b67e849b59" className="product_card-image-68" /> 
                                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/7d01/f3c6/64ed830030ef9978e06dee32887fadc4" className="product_card-image-8" /> 
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="product_card-6-1-1-1-1">
                              <div className="product_card-lorem_ipsum-000">
                                  Lorem Ipsum
                              </div>
                              <div className="product_card-lorem_ipsum-0000">
                                  Lorem Ipsum
                              </div>
                          </div>
                          <div className="product_card-6-1-1-1-2">
                              <div className="product_card-_123">{"₹ 123"}</div>
                              <div className="product_card-_123-0">{"₹ 123"}</div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="product_card-7">
              <div className="product_card-ellipse_1" /> 
              <div className="product_card-ellipse_8" /> 
              <div className="product_card-ellipse_9" /> 
          </div>
          <div className="product_card-8">
              <div className="product_card-rectangle_6">
                  <div className="product_card-8-0-0">
                      <div className="product_card-8-0-0-0">
                          <div className="product_card-8-0-0-0-0">
                              <div className="product_card-address-0">Address</div>
                          </div>
                          <div className="product_card-8-0-0-0-1">
                              <div className="product_card-12">
                                  123, New Colony , Delhi
                              </div>
                          </div>
                          <div className="product_card-8-0-0-0-2">
                              <div className="product_card-contact-00">Contact</div>
                          </div>
                          <div className="product_card-8-0-0-0-3">
                              <div className="product_card-email_greensum_gmail_com_cell_9">
                                  <div>{"Email : greensum@gmail.com"}</div>
                                  <div>{"Cell : +91 - 987654321"}</div>
                                  <div>{"Fax : greensum.io"}</div>
                              </div>
                          </div>
                      </div>
                      <div className="product_card-8-0-0-1">
                          <div className="product_card-8-0-0-1-0">
                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/80c5/cd9e/9811893e3828c2a729d6f4c088384115" className="product_card-image-4" /> 
                          </div>
                      </div>
                      <div className="product_card-8-0-0-2">
                          <div className="product_card-8-0-0-2-0">
                              <div className="product_card-useful_links-0">
                                  Useful links
                              </div>
                          </div>
                          <div className="product_card-8-0-0-2-1">
                              <div className="product_card-privacy_policy_terms_and_conditions_orders_and_tracking_return_policy_customer_care-0">
                                  <div>Privacy Policy</div>
                                  <div>Terms and Conditions</div>
                                  <div>Orders and Tracking</div>
                                  <div>Return Policy</div>
                                  <div>Customer Care</div>
                              </div>
                          </div>
                          <div className="product_card-8-0-0-2-2">
                              <div className="product_card-vector-0000025">
                                  <div className="product_card-8-0-0-2-2-0-0">
                                      <div className="product_card-vector-00000213" /> 
                                  </div>
                              </div>
                              <div className="product_card-vector-0000029">
                                  <div className="product_card-8-0-0-2-2-1-0">
                                      <div className="product_card-vector-0000010">
                                          <div className="product_card-8-0-0-2-2-1-0-0-0">
                                              <div className="product_card-vector-0000034" /> 
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="product_card-vector-0000024">
                                  <div className="product_card-8-0-0-2-2-2-0">
                                      <div className="product_card-vector-0000009" /> 
                                  </div>
                              </div>
                              <div className="product_card-vector-00000000">
                                  <div className="product_card-8-0-0-2-2-3-0">
                                      <div className="product_card-vector-0000035" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
