// Generated by greensum.pagedraw.json
import React from 'react';
import './product_card_3.css';


export default class Product_card_3 extends React.Component {
  render() {
    return (
      <div className="product_card_3-product_card_3">
          <div className="product_card_3-0">
              <div className="product_card_3-home-0">Home</div>
              <div className="product_card_3-shop-0">Shop</div>
              <div className="product_card_3-about-0">About </div>
              <div className="product_card_3-contact-0">Contact</div>
              <div className="product_card_3-recipes-0">recipes</div>
              <div className="product_card_3-0-5">
                  <div className="product_card_3-0-5-0">
                      <div className="product_card_3-vector-000">
                          <div className="product_card_3-0-5-0-0-0">
                              <div className="product_card_3-vector-00">
                                  <div className="product_card_3-0-5-0-0-0-0-0">
                                      <div className="product_card_3-vector-0" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="product_card_3-_9">+91 - 9876 54321</div>
              <div className="product_card_3-0-7">
                  <div className="product_card_3-0-7-0">
                      <div className="product_card_3-vector-00000">
                          <div className="product_card_3-0-7-0-0-0">
                              <div className="product_card_3-vector-0000" /> 
                          </div>
                      </div>
                  </div>
              </div>
              <div className="product_card_3-search-0">Search</div>
              <div className="product_card_3-0-9">
                  <div className="product_card_3-0-9-0">
                      <div className="product_card_3-vector-000000" /> 
                  </div>
              </div>
              <div className="product_card_3-account-0">Account</div>
              <div className="product_card_3-cart_0">{"Cart (0)"}</div>
          </div>
          <div className="product_card_3-1">
              <div className="product_card_3-rectangle_5" /> 
          </div>
          <div className="product_card_3-2">
              <div className="product_card_3-rectangle_3">
                  <div className="product_card_3-2-0-0">
                      <div className="product_card_3-our_store-0">Our store</div>
                      <div className="product_card_3-home_shop-0">
                          Home/ shop
                      </div>
                  </div>
              </div>
          </div>
          <div className="product_card_3-3">
              <div className="product_card_3-3-0">
                  <div className="product_card_3-3-0-0">
                      <div className="product_card_3-vector-000003" /> 
                  </div>
              </div>
              <div className="product_card_3-3-1">
                  <div className="product_card_3-3-1-0">
                      <div className="product_card_3-3-1-0-0">
                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/2b3c/60c0/30adb074ca23dd99d3328c1eeb1c3824" className="product_card_3-image-1" /> 
                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/7e04/0286/9fa2149ab91c641542be20e834d414f4" className="product_card_3-image-8" /> 
                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/c79b/1470/0296484e3e6c965b05769ab323bd56b0" className="product_card_3-image-0" /> 
                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/086e/4e61/1423a1ddbc26a688eb3b1932f60de061" className="product_card_3-image-4" /> 
                      </div>
                  </div>
              </div>
              <div className="product_card_3-3-2">
                  <div className="product_card_3-3-2-0">
                      <div className="product_card_3-vector-0000006" /> 
                  </div>
              </div>
              <div className="product_card_3-3-3">
                  <div className="product_card_3-3-3-0">
                      <div className="product_card_3-cheese_block-0">
                          Cheese Block
                      </div>
                  </div>
                  <div className="product_card_3-3-3-1">
                      <div className="product_card_3-_4">
                          {"( 4 customer reviews )"}
                      </div>
                  </div>
                  <div className="product_card_3-3-3-2">
                      <div className="product_card_3-3-3-2-0">
                          <div className="product_card_3-3-3-2-0-0">
                              <div className="product_card_3-3-3-2-0-0-0">
                                  <div className="product_card_3-15">  150</div>
                                  <div className="product_card_3-_-0">{"₹"}</div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="product_card_3-3-3-3">
                      <div className="product_card_3-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_fusce_scelerisque_libero_eget_pulvinar_vestibulum_nulla_egestas_pellentesque_molestie_fusce_neque_turpis-0">
                          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce scelerisque libero eget pulvinar vestibulum. Nulla egestas pellentesque molestie. Fusce neque turpis
                      </div>
                  </div>
                  <div className="product_card_3-3-3-4">
                      <div className="product_card_3-3-3-4-0">
                          <div className="product_card_3-3-3-4-0-0">
                              <div className="product_card_3-1-0">1</div>
                          </div>
                      </div>
                      <div className="product_card_3-3-3-4-1">
                          <div className="product_card_3-3-3-4-1-0">
                              <div className="product_card_3-3-3-4-1-0-0">
                                  <div className="product_card_3-rectangle_3-0" /> 
                                  <div className="product_card_3-buy_now-0">Buy now</div>
                              </div>
                          </div>
                      </div>
                      <div className="product_card_3-3-3-4-2">
                          <div className="product_card_3-3-3-4-2-0">
                              <div className="product_card_3-rectangle_9">
                                  <div className="product_card_3-3-3-4-2-0-0-0">
                                      <div className="product_card_3-vector-000001" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="product_card_3-3-3-5">
                      <div className="product_card_3-3-3-5-0">
                          <div className="product_card_3-3-3-5-0-0">
                              <div className="product_card_3-3-3-5-0-0-0">
                                  <div className="product_card_3-category_lorem_ipsum_dolor_tag_lorem_ipsum_lorem_ipsum_share_-0">
                                      <div>{"Category : Lorem ipsum dolor"}</div>
                                      <div>{"Tag : lorem Ipsum , lorem Ipsum"}</div>
                                      <div>{"Share :"}</div>
                                  </div>
                                  <div className="product_card_3-ic_baseline-mail-outline-0">
                                      <div className="product_card_3-3-3-5-0-0-0-1-0">
                                          <div className="product_card_3-vector-000002" /> 
                                      </div>
                                  </div>
                                  <div className="product_card_3-ant-design_message-outlined-0">
                                      <div className="product_card_3-3-3-5-0-0-0-2-0">
                                          <div className="product_card_3-vector-0000028" /> 
                                      </div>
                                  </div>
                                  <div className="product_card_3-vector-0000020">
                                      <div className="product_card_3-3-3-5-0-0-0-3-0">
                                          <div className="product_card_3-vector-0000035" /> 
                                      </div>
                                  </div>
                                  <div className="product_card_3-ellipse_7">
                                      <div className="product_card_3-3-3-5-0-0-0-4-0">
                                          <div className="product_card_3-vector-00000208" /> 
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="product_card_3-4">
              <div className="product_card_3-description-0">
                  Description
              </div>
              <div className="product_card_3-additional_information-0">
                  Additional Information
              </div>
              <div className="product_card_3-reviews_4">
                  {"Reviews (4)"}
              </div>
          </div>
          <div className="product_card_3-5">
              <div className="product_card_3-rectangle_1">
                  <div className="product_card_3-5-0-0">
                      <div className="product_card_3-5-0-0-0">
                          <div className="product_card_3-5-0-0-0-0">
                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/88eb/e0d6/02eb714bd65e74f8fb63cdc7e1e0594a" className="product_card_3-image-00" /> 
                          </div>
                      </div>
                      <div className="product_card_3-5-0-0-1">
                          <div className="product_card_3-5-0-0-1-0">
                              <div className="product_card_3-john_doe-0">John Doe</div>
                          </div>
                          <div className="product_card_3-5-0-0-1-1">
                              <div className="product_card_3-1_">1 Jan. 2020</div>
                          </div>
                          <div className="product_card_3-5-0-0-1-2">
                              <div className="product_card_3-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_fusce_scelerisque_libero_eget_pulvinar_vestibulum_nulla_egestas_pellentesque_molestie_fusce_neque_turpis-00">
                                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce scelerisque libero eget pulvinar vestibulum. Nulla egestas pellentesque molestie. Fusce neque turpis
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="product_card_3-5-0-1">
                      <div className="product_card_3-vector_2" /> 
                  </div>
                  <div className="product_card_3-5-0-2">
                      <div className="product_card_3-5-0-2-0">
                          <div className="product_card_3-5-0-2-0-0">
                              <div className="product_card_3-5-0-2-0-0-0">
                                  <div className="product_card_3-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_fusce_scelerisque_libero_eget_pulvinar_vestibulum_nulla_egestas_pellentesque_molestie_fusce_neque_turpis-000">
                                      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce scelerisque libero eget pulvinar vestibulum. Nulla egestas pellentesque molestie. Fusce neque turpis
                                  </div>
                                  <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/9265/4114/cfe4b0d82630ca9173be9100d0979d3f" className="product_card_3-image-2" /> 
                                  <div className="product_card_3-4_">4 Feb. 2020</div>
                                  <div className="product_card_3-harry_doe-0">Harry Doe</div>
                                  <div className="product_card_3-vector_3" /> 
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="product_card_3-5-0-3">
                      <div className="product_card_3-view_more-0">view more</div>
                  </div>
                  <div className="product_card_3-5-0-4">
                      <div className="product_card_3-add_a_review-0">
                          Add a review
                      </div>
                  </div>
                  <div className="product_card_3-5-0-5">
                      <div className="product_card_3-5-0-5-0">
                          <div className="product_card_3-5-0-5-0-0">
                              <div className="product_card_3-5-0-5-0-0-0">
                                  <div className="product_card_3-rating_-0">
                                      {"Rating : "}
                                  </div>
                                  <div className="product_card_3-vector-0000015" /> 
                                  <div className="product_card_3-vector-0000002" /> 
                              </div>
                          </div>
                      </div>
                      <div className="product_card_3-5-0-5-1">
                          <div className="product_card_3-5-0-5-1-0">
                              <div className="product_card_3-vector-00000155" /> 
                          </div>
                      </div>
                      <div className="product_card_3-5-0-5-2">
                          <div className="product_card_3-5-0-5-2-0">
                              <div className="product_card_3-vector-0000000" /> 
                          </div>
                      </div>
                      <div className="product_card_3-5-0-5-3">
                          <div className="product_card_3-5-0-5-3-0">
                              <div className="product_card_3-vector-0000019" /> 
                          </div>
                      </div>
                  </div>
                  <div className="product_card_3-5-0-6">
                      <div className="product_card_3-your_review_-0">
                          Your review * 
                      </div>
                  </div>
                  <div className="product_card_3-5-0-7">
                      <div className="product_card_3-rectangle_2" /> 
                  </div>
                  <div className="product_card_3-5-0-8">
                      <div className="product_card_3-name_-0">Name * </div>
                      <div className="product_card_3-email_-0">Email *</div>
                  </div>
                  <div className="product_card_3-5-0-9">
                      <div className="product_card_3-rectangle_27" /> 
                      <div className="product_card_3-rectangle_28" /> 
                  </div>
                  <div className="product_card_3-5-0-10">
                      <div className="product_card_3-5-0-10-0">
                          <div className="product_card_3-5-0-10-0-0">
                              <div className="product_card_3-5-0-10-0-0-0">
                                  <div className="product_card_3-rectangle_29" /> 
                                  <div className="product_card_3-submit-0">Submit</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="product_card_3-6">
              <div className="product_card_3-6-0">
                  <div className="product_card_3-6-0-0">
                      <div className="product_card_3-image-08">
                          <div className="product_card_3-6-0-0-0-0">
                              <div className="product_card_3-lorem_ipsum-0">
                                  Lorem Ipsum
                              </div>
                          </div>
                          <div className="product_card_3-6-0-0-0-1">
                              <div className="product_card_3-_1">{"₹ 123"}</div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="product_card_3-6-1">
                  <div className="product_card_3-6-1-0">
                      <div className="product_card_3-related_products-0">
                          Related  Products
                      </div>
                  </div>
                  <div className="product_card_3-6-1-1">
                      <div className="product_card_3-6-1-1-0">
                          <div className="product_card_3-6-1-1-0-0">
                              <div className="product_card_3-6-1-1-0-0-0">
                                  <div className="product_card_3-image-6">
                                      <div className="product_card_3-6-1-1-0-0-0-0-0">
                                          <div className="product_card_3-lorem_ipsum-00">
                                              Lorem Ipsum
                                          </div>
                                      </div>
                                  </div>
                                  <div className="product_card_3-_12">{"₹ 123"}</div>
                              </div>
                          </div>
                      </div>
                      <div className="product_card_3-6-1-1-1">
                          <div className="product_card_3-6-1-1-1-0">
                              <div className="product_card_3-6-1-1-1-0-0">
                                  <div className="product_card_3-6-1-1-1-0-0-0">
                                      <div className="product_card_3-6-1-1-1-0-0-0-0">
                                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/3706/c5fa/a53ea0617291a070161f46b67e849b59" className="product_card_3-image-5" /> 
                                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/7d01/f3c6/64ed830030ef9978e06dee32887fadc4" className="product_card_3-image-51" /> 
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="product_card_3-6-1-1-1-1">
                              <div className="product_card_3-lorem_ipsum-000">
                                  Lorem Ipsum
                              </div>
                              <div className="product_card_3-lorem_ipsum-0000">
                                  Lorem Ipsum
                              </div>
                          </div>
                          <div className="product_card_3-6-1-1-1-2">
                              <div className="product_card_3-_123">{"₹ 123"}</div>
                              <div className="product_card_3-_123-0">{"₹ 123"}</div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="product_card_3-7">
              <div className="product_card_3-ellipse_1" /> 
              <div className="product_card_3-ellipse_8" /> 
              <div className="product_card_3-ellipse_9" /> 
          </div>
          <div className="product_card_3-8">
              <div className="product_card_3-rectangle_6">
                  <div className="product_card_3-8-0-0">
                      <div className="product_card_3-8-0-0-0">
                          <div className="product_card_3-8-0-0-0-0">
                              <div className="product_card_3-address-0">Address</div>
                          </div>
                          <div className="product_card_3-8-0-0-0-1">
                              <div className="product_card_3-12">
                                  123, New Colony , Delhi
                              </div>
                          </div>
                          <div className="product_card_3-8-0-0-0-2">
                              <div className="product_card_3-contact-00">Contact</div>
                          </div>
                          <div className="product_card_3-8-0-0-0-3">
                              <div className="product_card_3-email_greensum_gmail_com_cell_9">
                                  <div>{"Email : greensum@gmail.com"}</div>
                                  <div>{"Cell : +91 - 987654321"}</div>
                                  <div>{"Fax : greensum.io"}</div>
                              </div>
                          </div>
                      </div>
                      <div className="product_card_3-8-0-0-1">
                          <div className="product_card_3-8-0-0-1-0">
                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/80c5/cd9e/9811893e3828c2a729d6f4c088384115" className="product_card_3-image-9" /> 
                          </div>
                      </div>
                      <div className="product_card_3-8-0-0-2">
                          <div className="product_card_3-8-0-0-2-0">
                              <div className="product_card_3-useful_links-0">
                                  Useful links
                              </div>
                          </div>
                          <div className="product_card_3-8-0-0-2-1">
                              <div className="product_card_3-privacy_policy_terms_and_conditions_orders_and_tracking_return_policy_customer_care-0">
                                  <div>Privacy Policy</div>
                                  <div>Terms and Conditions</div>
                                  <div>Orders and Tracking</div>
                                  <div>Return Policy</div>
                                  <div>Customer Care</div>
                              </div>
                          </div>
                          <div className="product_card_3-8-0-0-2-2">
                              <div className="product_card_3-vector-0000034">
                                  <div className="product_card_3-8-0-0-2-2-0-0">
                                      <div className="product_card_3-vector-00000156" /> 
                                  </div>
                              </div>
                              <div className="product_card_3-vector-00000022">
                                  <div className="product_card_3-8-0-0-2-2-1-0">
                                      <div className="product_card_3-vector-0000030">
                                          <div className="product_card_3-8-0-0-2-2-1-0-0-0">
                                              <div className="product_card_3-vector-0000013" /> 
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="product_card_3-vector-00000008">
                                  <div className="product_card_3-8-0-0-2-2-2-0">
                                      <div className="product_card_3-vector-0000024" /> 
                                  </div>
                              </div>
                              <div className="product_card_3-vector-0000001">
                                  <div className="product_card_3-8-0-0-2-2-3-0">
                                      <div className="product_card_3-vector-00000068" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
