// Generated by greensum.pagedraw.json
import React from 'react';
import './product_card_2.css';


export default class Product_card_2 extends React.Component {
  render() {
    return (
      <div className="product_card_2-product_card_2">
          <div className="product_card_2-0">
              <div className="product_card_2-home-0">Home</div>
              <div className="product_card_2-shop-0">Shop</div>
              <div className="product_card_2-about-0">About </div>
              <div className="product_card_2-contact-0">Contact</div>
              <div className="product_card_2-recipes-0">recipes</div>
              <div className="product_card_2-0-5">
                  <div className="product_card_2-0-5-0">
                      <div className="product_card_2-vector-000">
                          <div className="product_card_2-0-5-0-0-0">
                              <div className="product_card_2-vector-00">
                                  <div className="product_card_2-0-5-0-0-0-0-0">
                                      <div className="product_card_2-vector-0" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="product_card_2-_9">+91 - 9876 54321</div>
              <div className="product_card_2-0-7">
                  <div className="product_card_2-0-7-0">
                      <div className="product_card_2-vector-00000">
                          <div className="product_card_2-0-7-0-0-0">
                              <div className="product_card_2-vector-0000" /> 
                          </div>
                      </div>
                  </div>
              </div>
              <div className="product_card_2-search-0">Search</div>
              <div className="product_card_2-0-9">
                  <div className="product_card_2-0-9-0">
                      <div className="product_card_2-vector-000001" /> 
                  </div>
              </div>
              <div className="product_card_2-account-0">Account</div>
              <div className="product_card_2-cart_0">{"Cart (0)"}</div>
          </div>
          <div className="product_card_2-1">
              <div className="product_card_2-rectangle_5" /> 
          </div>
          <div className="product_card_2-2">
              <div className="product_card_2-rectangle_3">
                  <div className="product_card_2-2-0-0">
                      <div className="product_card_2-our_store-0">Our store</div>
                      <div className="product_card_2-home_shop-0">
                          Home/ shop
                      </div>
                  </div>
              </div>
          </div>
          <div className="product_card_2-3">
              <div className="product_card_2-3-0">
                  <div className="product_card_2-3-0-0">
                      <div className="product_card_2-vector-000000" /> 
                  </div>
              </div>
              <div className="product_card_2-3-1">
                  <div className="product_card_2-3-1-0">
                      <div className="product_card_2-3-1-0-0">
                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/2b3c/60c0/30adb074ca23dd99d3328c1eeb1c3824" className="product_card_2-image-7" /> 
                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/7e04/0286/9fa2149ab91c641542be20e834d414f4" className="product_card_2-image-1" /> 
                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/c79b/1470/0296484e3e6c965b05769ab323bd56b0" className="product_card_2-image-9" /> 
                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/086e/4e61/1423a1ddbc26a688eb3b1932f60de061" className="product_card_2-image-0" /> 
                      </div>
                  </div>
              </div>
              <div className="product_card_2-3-2">
                  <div className="product_card_2-3-2-0">
                      <div className="product_card_2-vector-000002" /> 
                  </div>
              </div>
              <div className="product_card_2-3-3">
                  <div className="product_card_2-3-3-0">
                      <div className="product_card_2-cheese_block-0">
                          Cheese Block
                      </div>
                  </div>
                  <div className="product_card_2-3-3-1">
                      <div className="product_card_2-_4">
                          {"( 4 customer reviews )"}
                      </div>
                  </div>
                  <div className="product_card_2-3-3-2">
                      <div className="product_card_2-3-3-2-0">
                          <div className="product_card_2-3-3-2-0-0">
                              <div className="product_card_2-3-3-2-0-0-0">
                                  <div className="product_card_2-15">  150</div>
                                  <div className="product_card_2-_-0">{"₹"}</div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="product_card_2-3-3-3">
                      <div className="product_card_2-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_fusce_scelerisque_libero_eget_pulvinar_vestibulum_nulla_egestas_pellentesque_molestie_fusce_neque_turpis-0">
                          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce scelerisque libero eget pulvinar vestibulum. Nulla egestas pellentesque molestie. Fusce neque turpis
                      </div>
                  </div>
                  <div className="product_card_2-3-3-4">
                      <div className="product_card_2-3-3-4-0">
                          <div className="product_card_2-3-3-4-0-0">
                              <div className="product_card_2-1-0">1</div>
                          </div>
                      </div>
                      <div className="product_card_2-3-3-4-1">
                          <div className="product_card_2-3-3-4-1-0">
                              <div className="product_card_2-3-3-4-1-0-0">
                                  <div className="product_card_2-rectangle_3-0" /> 
                                  <div className="product_card_2-buy_now-0">Buy now</div>
                              </div>
                          </div>
                      </div>
                      <div className="product_card_2-3-3-4-2">
                          <div className="product_card_2-3-3-4-2-0">
                              <div className="product_card_2-rectangle_9">
                                  <div className="product_card_2-3-3-4-2-0-0-0">
                                      <div className="product_card_2-vector-0000018" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="product_card_2-3-3-5">
                      <div className="product_card_2-3-3-5-0">
                          <div className="product_card_2-3-3-5-0-0">
                              <div className="product_card_2-3-3-5-0-0-0">
                                  <div className="product_card_2-category_lorem_ipsum_dolor_tag_lorem_ipsum_lorem_ipsum_share_-0">
                                      <div>{"Category : Lorem ipsum dolor"}</div>
                                      <div>{"Tag : lorem Ipsum , lorem Ipsum"}</div>
                                      <div>{"Share :"}</div>
                                  </div>
                                  <div className="product_card_2-ic_baseline-mail-outline-0">
                                      <div className="product_card_2-3-3-5-0-0-0-1-0">
                                          <div className="product_card_2-vector-000003" /> 
                                      </div>
                                  </div>
                                  <div className="product_card_2-ant-design_message-outlined-0">
                                      <div className="product_card_2-3-3-5-0-0-0-2-0">
                                          <div className="product_card_2-vector-0000005" /> 
                                      </div>
                                  </div>
                                  <div className="product_card_2-vector-0000025">
                                      <div className="product_card_2-3-3-5-0-0-0-3-0">
                                          <div className="product_card_2-vector-0000033" /> 
                                      </div>
                                  </div>
                                  <div className="product_card_2-ellipse_7">
                                      <div className="product_card_2-3-3-5-0-0-0-4-0">
                                          <div className="product_card_2-vector-0000013" /> 
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="product_card_2-4">
              <div className="product_card_2-vector-000004" /> 
          </div>
          <div className="product_card_2-5">
              <div className="product_card_2-description-0">
                  Description
              </div>
              <div className="product_card_2-additional_information-0">
                  Additional Information
              </div>
              <div className="product_card_2-reviews_4">
                  {"Reviews (4)"}
              </div>
          </div>
          <div className="product_card_2-6">
              <div className="product_card_2-rectangle_13">
                  <div className="product_card_2-6-0-0">
                      <div className="product_card_2-6-0-0-0">
                          <div className="product_card_2-weight_gm_dimensions_x_x_cheese_per_1">
                              <div>{"Weight : ## gm"}</div>
                              <br/>
                              <div>{"Dimensions : ## x ## x  ##"}</div>
                              <br/>
                              <div>{"Cheese per 100g :"}</div>
                              <br/>
                              <br/>
                              <div>{"	• Protein"}</div>
                              <br/>
                              <div>{" • Calories"}</div>
                              <br/>
                              <div>{" • Fat"}</div>
                              <br/>
                              <div>{"	• Carbohydrate"}</div>
                          </div>
                          <div className="product_card_2-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_fusce_scelerisque_libero_eget_pulvinar_vestibulum_nulla_egestas_pellentesque_molestie_fusce_neque_turpis_-0">
                              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce scelerisque libero eget pulvinar vestibulum. Nulla egestas pellentesque molestie. Fusce neque turpis.
                          </div>
                          <div className="product_card_2-rectangle_14">
                              <div className="product_card_2-6-0-0-0-2-0">
                                  <div className="product_card_2-rectangle_1" /> 
                              </div>
                          </div>
                          <div className="product_card_2-rectangle_16">
                              <div className="product_card_2-6-0-0-0-3-0">
                                  <div className="product_card_2-rectangle_2" /> 
                              </div>
                          </div>
                          <div className="product_card_2-rectangle_15">
                              <div className="product_card_2-6-0-0-0-4-0">
                                  <div className="product_card_2-rectangle_19" /> 
                              </div>
                          </div>
                          <div className="product_card_2-rectangle_17">
                              <div className="product_card_2-6-0-0-0-5-0">
                                  <div className="product_card_2-rectangle_21" /> 
                              </div>
                          </div>
                          <div className="product_card_2-fun_fact-0">Fun Fact </div>
                          <div className="product_card_2-ellipse_8" /> 
                          <div className="product_card_2-ellipse_9" /> 
                          <div className="product_card_2-ellipse_1" /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="product_card_2-7">
              <div className="product_card_2-7-0">
                  <div className="product_card_2-7-0-0">
                      <div className="product_card_2-image-12">
                          <div className="product_card_2-7-0-0-0-0">
                              <div className="product_card_2-lorem_ipsum-0">
                                  Lorem Ipsum
                              </div>
                          </div>
                          <div className="product_card_2-7-0-0-0-1">
                              <div className="product_card_2-_1">{"₹ 123"}</div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="product_card_2-7-1">
                  <div className="product_card_2-7-1-0">
                      <div className="product_card_2-related_products-0">
                          Related  Products
                      </div>
                  </div>
                  <div className="product_card_2-7-1-1">
                      <div className="product_card_2-7-1-1-0">
                          <div className="product_card_2-7-1-1-0-0">
                              <div className="product_card_2-7-1-1-0-0-0">
                                  <div className="product_card_2-image-19">
                                      <div className="product_card_2-7-1-1-0-0-0-0-0">
                                          <div className="product_card_2-lorem_ipsum-00">
                                              Lorem Ipsum
                                          </div>
                                      </div>
                                  </div>
                                  <div className="product_card_2-_12">{"₹ 123"}</div>
                              </div>
                          </div>
                      </div>
                      <div className="product_card_2-7-1-1-1">
                          <div className="product_card_2-7-1-1-1-0">
                              <div className="product_card_2-7-1-1-1-0-0">
                                  <div className="product_card_2-7-1-1-1-0-0-0">
                                      <div className="product_card_2-7-1-1-1-0-0-0-0">
                                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/3706/c5fa/a53ea0617291a070161f46b67e849b59" className="product_card_2-image-8" /> 
                                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/7d01/f3c6/64ed830030ef9978e06dee32887fadc4" className="product_card_2-image-03" /> 
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="product_card_2-7-1-1-1-1">
                              <div className="product_card_2-lorem_ipsum-000">
                                  Lorem Ipsum
                              </div>
                              <div className="product_card_2-lorem_ipsum-0000">
                                  Lorem Ipsum
                              </div>
                          </div>
                          <div className="product_card_2-7-1-1-1-2">
                              <div className="product_card_2-_123">{"₹ 123"}</div>
                              <div className="product_card_2-_123-0">{"₹ 123"}</div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="product_card_2-8">
              <div className="product_card_2-ellipse_10" /> 
              <div className="product_card_2-ellipse_8-0" /> 
              <div className="product_card_2-ellipse_9-0" /> 
          </div>
          <div className="product_card_2-9">
              <div className="product_card_2-9-0">
                  <div className="product_card_2-9-0-0">
                      <div className="product_card_2-9-0-0-0">
                          <div className="product_card_2-rectangle_6" /> 
                          <div className="product_card_2-rectangle_67">
                              <div className="product_card_2-9-0-0-0-1-0">
                                  <div className="product_card_2-9-0-0-0-1-0-0">
                                      <div className="product_card_2-9-0-0-0-1-0-0-0">
                                          <div className="product_card_2-9-0-0-0-1-0-0-0-0">
                                              <div className="product_card_2-9-0-0-0-1-0-0-0-0-0">
                                                  <div className="product_card_2-9-0-0-0-1-0-0-0-0-0-0">
                                                      <div className="product_card_2-address-0">Address</div>
                                                      <div className="product_card_2-address-00">Address</div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div className="product_card_2-9-0-0-0-1-0-0-1">
                                          <div className="product_card_2-9-0-0-0-1-0-0-1-0">
                                              <div className="product_card_2-9-0-0-0-1-0-0-1-0-0">
                                                  <div className="product_card_2-9-0-0-0-1-0-0-1-0-0-0">
                                                      <div className="product_card_2-12">
                                                          123, New Colony , Delhi
                                                      </div>
                                                      <div className="product_card_2-123">
                                                          123, New Colony , Delhi
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div className="product_card_2-9-0-0-0-1-0-0-2">
                                          <div className="product_card_2-9-0-0-0-1-0-0-2-0">
                                              <div className="product_card_2-9-0-0-0-1-0-0-2-0-0">
                                                  <div className="product_card_2-9-0-0-0-1-0-0-2-0-0-0">
                                                      <div className="product_card_2-contact-00">Contact</div>
                                                      <div className="product_card_2-contact-000">Contact</div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div className="product_card_2-9-0-0-0-1-0-0-3">
                                          <div className="product_card_2-9-0-0-0-1-0-0-3-0">
                                              <div className="product_card_2-9-0-0-0-1-0-0-3-0-0">
                                                  <div className="product_card_2-9-0-0-0-1-0-0-3-0-0-0">
                                                      <div className="product_card_2-email_greensum_gmail_com_cell_9">
                                                          <div>{"Email : greensum@gmail.com"}</div>
                                                          <div>{"Cell : +91 - 987654321"}</div>
                                                          <div>{"Fax : greensum.io"}</div>
                                                      </div>
                                                      <div className="product_card_2-email_greensum_gmail_com_cell_91">
                                                          <div>{"Email : greensum@gmail.com"}</div>
                                                          <div>{"Cell : +91 - 987654321"}</div>
                                                          <div>{"Fax : greensum.io"}</div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="product_card_2-9-0-0-0-1-0-1">
                                      <div className="product_card_2-9-0-0-0-1-0-1-0">
                                          <div className="product_card_2-9-0-0-0-1-0-1-0-0">
                                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/80c5/cd9e/9811893e3828c2a729d6f4c088384115" className="product_card_2-image-88" /> 
                                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/80c5/cd9e/9811893e3828c2a729d6f4c088384115" className="product_card_2-image-79" /> 
                                          </div>
                                      </div>
                                  </div>
                                  <div className="product_card_2-9-0-0-0-1-0-2">
                                      <div className="product_card_2-9-0-0-0-1-0-2-0">
                                          <div className="product_card_2-9-0-0-0-1-0-2-0-0">
                                              <div className="product_card_2-9-0-0-0-1-0-2-0-0-0">
                                                  <div className="product_card_2-9-0-0-0-1-0-2-0-0-0-0">
                                                      <div className="product_card_2-useful_links-0">
                                                          Useful links
                                                      </div>
                                                      <div className="product_card_2-useful_links-00">
                                                          Useful links
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div className="product_card_2-9-0-0-0-1-0-2-1">
                                          <div className="product_card_2-9-0-0-0-1-0-2-1-0">
                                              <div className="product_card_2-9-0-0-0-1-0-2-1-0-0">
                                                  <div className="product_card_2-9-0-0-0-1-0-2-1-0-0-0">
                                                      <div className="product_card_2-privacy_policy_terms_and_conditions_orders_and_tracking_return_policy_customer_care-0">
                                                          <div>Privacy Policy</div>
                                                          <div>Terms and Conditions</div>
                                                          <div>Orders and Tracking</div>
                                                          <div>Return Policy</div>
                                                          <div>Customer Care</div>
                                                      </div>
                                                      <div className="product_card_2-privacy_policy_terms_and_conditions_orders_and_tracking_return_policy_customer_care-00">
                                                          <div>Privacy Policy</div>
                                                          <div>Terms and Conditions</div>
                                                          <div>Orders and Tracking</div>
                                                          <div>Return Policy</div>
                                                          <div>Customer Care</div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div className="product_card_2-9-0-0-0-1-0-2-2">
                                          <div className="product_card_2-9-0-0-0-1-0-2-2-0">
                                              <div className="product_card_2-9-0-0-0-1-0-2-2-0-0">
                                                  <div className="product_card_2-9-0-0-0-1-0-2-2-0-0-0">
                                                      <div className="product_card_2-vector-0000035" /> 
                                                      <div className="product_card_2-vector-00000338">
                                                          <div className="product_card_2-9-0-0-0-1-0-2-2-0-0-0-1-0">
                                                              <div className="product_card_2-9-0-0-0-1-0-2-2-0-0-0-1-0-0">
                                                                  <div className="product_card_2-vector-0000020" /> 
                                                                  <div className="product_card_2-vector-0000011" /> 
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                          <div className="product_card_2-9-0-0-0-1-0-2-2-1">
                                              <div className="product_card_2-9-0-0-0-1-0-2-2-1-0">
                                                  <div className="product_card_2-9-0-0-0-1-0-2-2-1-0-0">
                                                      <div className="product_card_2-vector-0000022" /> 
                                                      <div className="product_card_2-vector-0000009">
                                                          <div className="product_card_2-9-0-0-0-1-0-2-2-1-0-0-1-0">
                                                              <div className="product_card_2-9-0-0-0-1-0-2-2-1-0-0-1-0-0">
                                                                  <div className="product_card_2-vector-00000353" /> 
                                                                  <div className="product_card_2-vector-00000115">
                                                                      <div className="product_card_2-9-0-0-0-1-0-2-2-1-0-0-1-0-0-1-0">
                                                                          <div className="product_card_2-vector-0000016" /> 
                                                                      </div>
                                                                      <div className="product_card_2-9-0-0-0-1-0-2-2-1-0-0-1-0-0-1-1">
                                                                          <div className="product_card_2-vector-0000032" /> 
                                                                      </div>
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                          <div className="product_card_2-9-0-0-0-1-0-2-2-2">
                                              <div className="product_card_2-9-0-0-0-1-0-2-2-2-0">
                                                  <div className="product_card_2-9-0-0-0-1-0-2-2-2-0-0">
                                                      <div className="product_card_2-vector-00000358" /> 
                                                      <div className="product_card_2-vector-0000029">
                                                          <div className="product_card_2-9-0-0-0-1-0-2-2-2-0-0-1-0">
                                                              <div className="product_card_2-9-0-0-0-1-0-2-2-2-0-0-1-0-0">
                                                                  <div className="product_card_2-vector-0000034" /> 
                                                                  <div className="product_card_2-vector-00000134" /> 
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                          <div className="product_card_2-9-0-0-0-1-0-2-2-3">
                                              <div className="product_card_2-9-0-0-0-1-0-2-2-3-0">
                                                  <div className="product_card_2-9-0-0-0-1-0-2-2-3-0-0">
                                                      <div className="product_card_2-vector-0000028" /> 
                                                      <div className="product_card_2-vector-0000007">
                                                          <div className="product_card_2-9-0-0-0-1-0-2-2-3-0-0-1-0">
                                                              <div className="product_card_2-9-0-0-0-1-0-2-2-3-0-0-1-0-0">
                                                                  <div className="product_card_2-vector-0000021" /> 
                                                                  <div className="product_card_2-vector-00000162" /> 
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
