// Generated by greensum.pagedraw.json
import React from 'react';
import './products_2.css';


export default class Products_2 extends React.Component {
  render() {
    return (
      <div className="products_2-products_2">
          <div className="products_2-0">
              <div className="products_2-home-0">Home</div>
              <div className="products_2-shop-0">Shop</div>
              <div className="products_2-about-0">About </div>
              <div className="products_2-contact-0">Contact</div>
              <div className="products_2-recipes-0">recipes</div>
              <div className="products_2-0-5">
                  <div className="products_2-0-5-0">
                      <div className="products_2-vector-000">
                          <div className="products_2-0-5-0-0-0">
                              <div className="products_2-vector-00">
                                  <div className="products_2-0-5-0-0-0-0-0">
                                      <div className="products_2-vector-0" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="products_2-_9">+91 - 9876 54321</div>
              <div className="products_2-0-7">
                  <div className="products_2-0-7-0">
                      <div className="products_2-vector-00000">
                          <div className="products_2-0-7-0-0-0">
                              <div className="products_2-vector-0000" /> 
                          </div>
                      </div>
                  </div>
              </div>
              <div className="products_2-search-0">Search</div>
              <div className="products_2-0-9">
                  <div className="products_2-0-9-0">
                      <div className="products_2-vector-000002" /> 
                  </div>
              </div>
              <div className="products_2-account-0">Account</div>
              <div className="products_2-cart_0">{"Cart (0)"}</div>
          </div>
          <div className="products_2-1">
              <div className="products_2-rectangle_5" /> 
          </div>
          <div className="products_2-2">
              <div className="products_2-rectangle_3">
                  <div className="products_2-2-0-0">
                      <div className="products_2-our_store-0">Our store</div>
                      <div className="products_2-home_shop-0">Home/ shop</div>
                  </div>
              </div>
          </div>
          <div className="products_2-3">
              <div className="products_2-recently_viewed-0">
                  Recently  viewed
              </div>
          </div>
          <div className="products_2-4">
              <div className="products_2-rectangle_31">
                  <div className="products_2-4-0-0">
                      <div className="products_2-vector-0000022" /> 
                  </div>
                  <div className="products_2-4-0-1">
                      <div className="products_2-lorem_ipsum-0">Lorem Ipsum</div>
                  </div>
                  <div className="products_2-4-0-2">
                      <div className="products_2-_1">{"₹ 123"}</div>
                  </div>
              </div>
              <div className="products_2-rectangle_32">
                  <div className="products_2-4-1-0">
                      <div className="products_2-vector-0000026" /> 
                  </div>
                  <div className="products_2-4-1-1">
                      <div className="products_2-lorem_ipsum-00">
                          Lorem Ipsum
                      </div>
                  </div>
                  <div className="products_2-4-1-2">
                      <div className="products_2-_12">{"₹ 123"}</div>
                  </div>
              </div>
          </div>
          <div className="products_2-5">
              <div className="products_2-rectangle_34">
                  <div className="products_2-5-0-0">
                      <div className="products_2-vector-000003" /> 
                  </div>
                  <div className="products_2-5-0-1">
                      <div className="products_2-lorem_ipsum-000">
                          Lorem Ipsum
                      </div>
                  </div>
                  <div className="products_2-5-0-2">
                      <div className="products_2-_123">{"₹ 123"}</div>
                  </div>
              </div>
              <div className="products_2-rectangle_33">
                  <div className="products_2-5-1-0">
                      <div className="products_2-vector-000000" /> 
                  </div>
                  <div className="products_2-5-1-1">
                      <div className="products_2-lorem_ipsum-0000">
                          Lorem Ipsum
                      </div>
                  </div>
                  <div className="products_2-5-1-2">
                      <div className="products_2-_123-0">{"₹ 123"}</div>
                  </div>
              </div>
          </div>
          <div className="products_2-6">
              <div className="products_2-6-0">
                  <div className="products_2-6-0-0">
                      <div className="products_2-all-0">All</div>
                  </div>
              </div>
              <div className="products_2-6-1">
                  <div className="products_2-6-1-0">
                      <div className="products_2-lorem_ipsum-00000">
                          lorem Ipsum
                      </div>
                  </div>
              </div>
              <div className="products_2-6-2">
                  <div className="products_2-6-2-0">
                      <div className="products_2-lorem_ipsum-000003">
                          lorem Ipsum
                      </div>
                  </div>
              </div>
              <div className="products_2-6-3">
                  <div className="products_2-6-3-0">
                      <div className="products_2-lorem_ipsum-000001">
                          lorem Ipsum
                      </div>
                  </div>
              </div>
              <div className="products_2-6-4">
                  <div className="products_2-6-4-0">
                      <div className="products_2-lorem_ipsum-000000">
                          lorem Ipsum
                      </div>
                  </div>
              </div>
              <div className="products_2-6-5">
                  <div className="products_2-6-5-0">
                      <div className="products_2-lorem_ipsum-0000038">
                          lorem Ipsum
                      </div>
                  </div>
              </div>
              <div className="products_2-6-6">
                  <div className="products_2-6-6-0">
                      <div className="products_2-6-6-0-0">
                          <div className="products_2-rectangle_2">
                              <div className="products_2-6-6-0-0-0-0">
                                  <div className="products_2-vector_4" /> 
                              </div>
                          </div>
                          <div className="products_2-price_low_to_high-0">
                              {"Price : Low to high"}
                          </div>
                      </div>
                  </div>
              </div>
              <div className="products_2-rectangle_35">
                  <div className="products_2-6-7-0">
                      <div className="products_2-vector-0000023" /> 
                  </div>
              </div>
              <div className="products_2-rectangle_36">
                  <div className="products_2-6-8-0">
                      <div className="products_2-vector-0000030" /> 
                  </div>
              </div>
          </div>
          <div className="products_2-7">
              <div className="products_2-7-0">
                  <div className="products_2-7-0-0">
                      <div className="products_2-7-0-0-0">
                          <div className="products_2-rectangle_37">
                              <div className="products_2-7-0-0-0-0-0">
                                  <div className="products_2-lorem_ipsum-0000008">
                                      Lorem Ipsum
                                  </div>
                              </div>
                              <div className="products_2-7-0-0-0-0-1">
                                  <div className="products_2-_123-00">{"₹ 123"}</div>
                              </div>
                              <div className="products_2-7-0-0-0-0-2">
                                  <div className="products_2-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_fusce_scelerisque_libero_eget_pulvinar_vestibulum_nulla_egestas_pellentesque_molestie_fusce_neque_turpis-0">
                                      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce scelerisque libero eget pulvinar vestibulum. Nulla egestas pellentesque molestie. Fusce neque turpis
                                  </div>
                              </div>
                          </div>
                          <div className="products_2-rectangle_4">
                              <div className="products_2-7-0-0-0-1-0">
                                  <div className="products_2-vector-000001" /> 
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="products_2-8">
              <div className="products_2-8-0">
                  <div className="products_2-8-0-0">
                      <div className="products_2-8-0-0-0">
                          <div className="products_2-rectangle_38">
                              <div className="products_2-8-0-0-0-0-0">
                                  <div className="products_2-lorem_ipsum-0000017">
                                      Lorem Ipsum
                                  </div>
                              </div>
                              <div className="products_2-8-0-0-0-0-1">
                                  <div className="products_2-_123-000">{"₹ 123"}</div>
                              </div>
                              <div className="products_2-8-0-0-0-0-2">
                                  <div className="products_2-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_fusce_scelerisque_libero_eget_pulvinar_vestibulum_nulla_egestas_pellentesque_molestie_fusce_neque_turpis-00">
                                      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce scelerisque libero eget pulvinar vestibulum. Nulla egestas pellentesque molestie. Fusce neque turpis
                                  </div>
                              </div>
                          </div>
                          <div className="products_2-rectangle_43">
                              <div className="products_2-8-0-0-0-1-0">
                                  <div className="products_2-vector-0000010" /> 
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="products_2-9">
              <div className="products_2-9-0">
                  <div className="products_2-9-0-0">
                      <div className="products_2-9-0-0-0">
                          <div className="products_2-rectangle_39">
                              <div className="products_2-9-0-0-0-0-0">
                                  <div className="products_2-lorem_ipsum-0000033">
                                      Lorem Ipsum
                                  </div>
                              </div>
                              <div className="products_2-9-0-0-0-0-1">
                                  <div className="products_2-_123-0000">{"₹ 123"}</div>
                              </div>
                              <div className="products_2-9-0-0-0-0-2">
                                  <div className="products_2-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_fusce_scelerisque_libero_eget_pulvinar_vestibulum_nulla_egestas_pellentesque_molestie_fusce_neque_turpis-000">
                                      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce scelerisque libero eget pulvinar vestibulum. Nulla egestas pellentesque molestie. Fusce neque turpis
                                  </div>
                              </div>
                          </div>
                          <div className="products_2-rectangle_42">
                              <div className="products_2-9-0-0-0-1-0">
                                  <div className="products_2-vector-0000025" /> 
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="products_2-10">
              <div className="products_2-10-0">
                  <div className="products_2-10-0-0">
                      <div className="products_2-10-0-0-0">
                          <div className="products_2-1_">1   2   3 .... 10</div>
                          <div className="products_2-rectangle_49" /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="products_2-11">
              <div className="products_2-11-0">
                  <div className="products_2-11-0-0">
                      <div className="products_2-image-4">
                          <div className="products_2-11-0-0-0-0">
                              <div className="products_2-lorem_ipsum-000004">
                                  Lorem Ipsum
                              </div>
                          </div>
                          <div className="products_2-11-0-0-0-1">
                              <div className="products_2-_123-00000">{"₹ 123"}</div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="products_2-11-1">
                  <div className="products_2-11-1-0">
                      <div className="products_2-related_products-0">
                          Related  Products
                      </div>
                  </div>
                  <div className="products_2-11-1-1">
                      <div className="products_2-11-1-1-0">
                          <div className="products_2-11-1-1-0-0">
                              <div className="products_2-11-1-1-0-0-0">
                                  <div className="products_2-image-5">
                                      <div className="products_2-11-1-1-0-0-0-0-0">
                                          <div className="products_2-lorem_ipsum-000002">
                                              Lorem Ipsum
                                          </div>
                                      </div>
                                  </div>
                                  <div className="products_2-_123-000004">{"₹ 123"}</div>
                              </div>
                          </div>
                      </div>
                      <div className="products_2-11-1-1-1">
                          <div className="products_2-11-1-1-1-0">
                              <div className="products_2-11-1-1-1-0-0">
                                  <div className="products_2-11-1-1-1-0-0-0">
                                      <div className="products_2-11-1-1-1-0-0-0-0">
                                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/3706/c5fa/a53ea0617291a070161f46b67e849b59" className="products_2-image-3" /> 
                                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/7d01/f3c6/64ed830030ef9978e06dee32887fadc4" className="products_2-image-9" /> 
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="products_2-11-1-1-1-1">
                              <div className="products_2-lorem_ipsum-0000042">
                                  Lorem Ipsum
                              </div>
                              <div className="products_2-lorem_ipsum-0000000">
                                  Lorem Ipsum
                              </div>
                          </div>
                          <div className="products_2-11-1-1-1-2">
                              <div className="products_2-_123-000000">{"₹ 123"}</div>
                              <div className="products_2-_123-0000007">{"₹ 123"}</div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="products_2-12">
              <div className="products_2-ellipse_1" /> 
              <div className="products_2-ellipse_8" /> 
              <div className="products_2-ellipse_9" /> 
          </div>
          <div className="products_2-13">
              <div className="products_2-rectangle_6">
                  <div className="products_2-13-0-0">
                      <div className="products_2-13-0-0-0">
                          <div className="products_2-13-0-0-0-0">
                              <div className="products_2-address-0">Address</div>
                          </div>
                          <div className="products_2-13-0-0-0-1">
                              <div className="products_2-123">
                                  123, New Colony , Delhi
                              </div>
                          </div>
                          <div className="products_2-13-0-0-0-2">
                              <div className="products_2-contact-00">Contact</div>
                          </div>
                          <div className="products_2-13-0-0-0-3">
                              <div className="products_2-email_greensum_gmail_com_cell_9">
                                  <div>{"Email : greensum@gmail.com"}</div>
                                  <div>{"Cell : +91 - 987654321"}</div>
                                  <div>{"Fax : greensum.io"}</div>
                              </div>
                          </div>
                      </div>
                      <div className="products_2-13-0-0-1">
                          <div className="products_2-13-0-0-1-0">
                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/80c5/cd9e/9811893e3828c2a729d6f4c088384115" className="products_2-image-44" /> 
                          </div>
                      </div>
                      <div className="products_2-13-0-0-2">
                          <div className="products_2-13-0-0-2-0">
                              <div className="products_2-useful_links-0">
                                  Useful links
                              </div>
                          </div>
                          <div className="products_2-13-0-0-2-1">
                              <div className="products_2-privacy_policy_terms_and_conditions_orders_and_tracking_return_policy_customer_care-0">
                                  <div>Privacy Policy</div>
                                  <div>Terms and Conditions</div>
                                  <div>Orders and Tracking</div>
                                  <div>Return Policy</div>
                                  <div>Customer Care</div>
                              </div>
                          </div>
                          <div className="products_2-13-0-0-2-2">
                              <div className="products_2-vector-0000011">
                                  <div className="products_2-13-0-0-2-2-0-0">
                                      <div className="products_2-vector-0000014" /> 
                                  </div>
                              </div>
                              <div className="products_2-vector-0000031">
                                  <div className="products_2-13-0-0-2-2-1-0">
                                      <div className="products_2-vector-0000038">
                                          <div className="products_2-13-0-0-2-2-1-0-0-0">
                                              <div className="products_2-vector-00000302" /> 
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="products_2-vector-0000002">
                                  <div className="products_2-13-0-0-2-2-2-0">
                                      <div className="products_2-vector-00000300" /> 
                                  </div>
                              </div>
                              <div className="products_2-vector-0000019">
                                  <div className="products_2-13-0-0-2-2-3-0">
                                      <div className="products_2-vector-000004" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
