// Generated by greensum.pagedraw.json
import React from 'react';
import './recipes.css';


export default class Recipes extends React.Component {
  render() {
    return (
      <div className="recipes-recipes-000">
          <div className="recipes-0">
              <div className="recipes-home-0">Home</div>
              <div className="recipes-shop-0">Shop</div>
              <div className="recipes-about-0">About </div>
              <div className="recipes-contact-0">Contact</div>
              <div className="recipes-recipes-0">Recipes</div>
              <div className="recipes-0-5">
                  <div className="recipes-0-5-0">
                      <div className="recipes-vector-000">
                          <div className="recipes-0-5-0-0-0">
                              <div className="recipes-vector-00">
                                  <div className="recipes-0-5-0-0-0-0-0">
                                      <div className="recipes-vector-0" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="recipes-_9">+91 - 9876 54321</div>
              <div className="recipes-0-7">
                  <div className="recipes-0-7-0">
                      <div className="recipes-vector-00000">
                          <div className="recipes-0-7-0-0-0">
                              <div className="recipes-vector-0000" /> 
                          </div>
                      </div>
                  </div>
              </div>
              <div className="recipes-search-0">Search</div>
              <div className="recipes-0-9">
                  <div className="recipes-0-9-0">
                      <div className="recipes-vector-000001" /> 
                  </div>
              </div>
              <div className="recipes-account-0">Account</div>
              <div className="recipes-cart_0">{"Cart (0)"}</div>
          </div>
          <div className="recipes-1">
              <div className="recipes-rectangle_3">
                  <div className="recipes-1-0-0">
                      <div className="recipes-recipes-00">Recipes</div>
                      <div className="recipes-home_recipes-0">Home/ recipes</div>
                  </div>
              </div>
          </div>
          <div className="recipes-2">
              <div className="recipes-2-0">
                  <div className="recipes-2-0-0">
                      <div className="recipes-all-0">All</div>
                  </div>
              </div>
              <div className="recipes-2-1">
                  <div className="recipes-2-1-0">
                      <div className="recipes-vector_4" /> 
                  </div>
              </div>
              <div className="recipes-2-2">
                  <div className="recipes-2-2-0">
                      <div className="recipes-lorem_ipsum-0">lorem Ipsum</div>
                  </div>
              </div>
              <div className="recipes-2-3">
                  <div className="recipes-2-3-0">
                      <div className="recipes-vector-000003" /> 
                  </div>
              </div>
              <div className="recipes-search_here-0">Search here</div>
          </div>
          <div className="recipes-3">
              <div className="recipes-lorem_ipsum_dolor-0">
                  Lorem Ipsum Dolor
              </div>
          </div>
          <div className="recipes-4">
              <div className="recipes-vector-0000015">
                  <div className="recipes-4-0-0">
                      <div className="recipes-vector-000004" /> 
                  </div>
              </div>
              <div className="recipes-4-1">
                  <div className="recipes-4-1-0">
                      <div className="recipes-20">20 mins</div>
                  </div>
              </div>
              <div className="recipes-4-2">
                  <div className="recipes-4-2-0">
                      <div className="recipes-vector-000000" /> 
                  </div>
              </div>
              <div className="recipes-4-3">
                  <div className="recipes-4-3-0">
                      <div className="recipes-30">300 calories</div>
                  </div>
              </div>
          </div>
          <div className="recipes-5">
              <div className="recipes-5-0">
                  <div className="recipes-5-0-0">
                      <div className="recipes-vector-000002" /> 
                  </div>
              </div>
              <div className="recipes-5-1">
                  <div className="recipes-5-1-0">
                      <div className="recipes-vector-0000024" /> 
                  </div>
                  <div className="recipes-5-1-1">
                      <div className="recipes-5-1-1-0">
                          <div className="recipes-5-1-1-0-0">
                              <div className="recipes-5-1-1-0-0-0">
                                  <div className="recipes-vector-0000026" /> 
                                  <div className="recipes-vector-0000002" /> 
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="recipes-5-1-2">
                      <div className="recipes-5-1-2-0">
                          <div className="recipes-5-1-2-0-0">
                              <div className="recipes-5-1-2-0-0-0">
                                  <div className="recipes-vector-0000035" /> 
                                  <div className="recipes-vector-0000019" /> 
                                  <div className="recipes-vector-00000359" /> 
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="recipes-5-2">
                  <div className="recipes-5-2-0">
                      <div className="recipes-rectangle_9">
                          <div className="recipes-5-2-0-0-0">
                              <div className="recipes-vector-0000038" /> 
                          </div>
                      </div>
                  </div>
              </div>
              <div className="recipes-5-3">
                  <div className="recipes-5-3-0">
                      <div className="recipes-5-3-0-0">
                          <div className="recipes-rectangle_5">
                              <div className="recipes-5-3-0-0-0-0">
                                  <div className="recipes-lorem_ipsum-00">Lorem Ipsum</div>
                              </div>
                              <div className="recipes-5-3-0-0-0-1">
                                  <div className="recipes-5-3-0-0-0-1-0">
                                      <div className="recipes-5-3-0-0-0-1-0-0">
                                          <div className="recipes-1-0">1</div>
                                      </div>
                                  </div>
                                  <div className="recipes-5-3-0-0-0-1-1">
                                      <div className="recipes-5-3-0-0-0-1-1-0">
                                          <div className="recipes-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_fusce_scelerisque_libero_eget_pulvinar_vestibulum_nulla_egestas_pellentesque_molestie_fusce_neque_turpis-0">
                                              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce scelerisque libero eget pulvinar vestibulum. Nulla egestas pellentesque molestie. Fusce neque turpis
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="recipes-5-3-0-0-0-2">
                                  <div className="recipes-2-00">2</div>
                                  <div className="recipes-5-3-0-0-0-2-1">
                                      <div className="recipes-5-3-0-0-0-2-1-0">
                                          <div className="recipes-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_-0">
                                              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="recipes-5-3-0-0-0-3">
                                  <div className="recipes-3-0">3</div>
                                  <div className="recipes-5-3-0-0-0-3-1">
                                      <div className="recipes-5-3-0-0-0-3-1-0">
                                          <div className="recipes-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_-00">
                                              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="recipes-5-3-0-0-0-4">
                                  <div className="recipes-5-3-0-0-0-4-0">
                                      <div className="recipes-5-3-0-0-0-4-0-0">
                                          <div className="recipes-4-0">4</div>
                                      </div>
                                  </div>
                                  <div className="recipes-5-3-0-0-0-4-1">
                                      <div className="recipes-5-3-0-0-0-4-1-0">
                                          <div className="recipes-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_fusce_scelerisque_libero_eget_pulvinar_vestibulum_-0">
                                              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce scelerisque libero eget pulvinar vestibulum.
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="recipes-5-3-0-0-0-5">
                                  <div className="recipes-enjoy_your_meal_d-0">
                                      {"Enjoy your meal :D"}
                                  </div>
                              </div>
                          </div>
                          <div className="recipes-rectangle_4">
                              <div className="recipes-5-3-0-0-1-0">
                                  <div className="recipes-vector-0000018" /> 
                              </div>
                              <div className="recipes-5-3-0-0-1-1">
                                  <div className="recipes-ellipse_1" /> 
                                  <div className="recipes-ellipse_8" /> 
                                  <div className="recipes-ellipse_9" /> 
                              </div>
                          </div>
                          <div className="recipes-vector-0000029" /> 
                          <div className="recipes-vector-0000013" /> 
                      </div>
                  </div>
              </div>
              <div className="recipes-5-4">
                  <div className="recipes-5-4-0">
                      <div className="recipes-5-4-0-0">
                          <div className="recipes-vector-00000188" /> 
                          <div className="recipes-vector-0000008" /> 
                          <div className="recipes-vector-0000014" /> 
                          <div className="recipes-vector-0000007" /> 
                          <div className="recipes-vector-0000025" /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="recipes-6">
              <div className="recipes-6-0">
                  <div className="recipes-6-0-0">
                      <div className="recipes-vector_6" /> 
                  </div>
              </div>
              <div className="recipes-previous-0">Previous</div>
              <div className="recipes-next-0">Next</div>
              <div className="recipes-6-3">
                  <div className="recipes-6-3-0">
                      <div className="recipes-vector_5" /> 
                  </div>
              </div>
          </div>
          <div className="recipes-7">
              <div className="recipes-rectangle_6">
                  <div className="recipes-7-0-0">
                      <div className="recipes-7-0-0-0">
                          <div className="recipes-7-0-0-0-0">
                              <div className="recipes-address-0">Address</div>
                          </div>
                          <div className="recipes-7-0-0-0-1">
                              <div className="recipes-12">123, New Colony , Delhi</div>
                          </div>
                          <div className="recipes-7-0-0-0-2">
                              <div className="recipes-contact-00">Contact</div>
                          </div>
                          <div className="recipes-7-0-0-0-3">
                              <div className="recipes-email_greensum_gmail_com_cell_9">
                                  <div>{"Email : greensum@gmail.com"}</div>
                                  <div>{"Cell : +91 - 987654321"}</div>
                                  <div>{"Fax : greensum.io"}</div>
                              </div>
                          </div>
                      </div>
                      <div className="recipes-7-0-0-1">
                          <div className="recipes-7-0-0-1-0">
                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/80c5/cd9e/9811893e3828c2a729d6f4c088384115" className="recipes-image-1" /> 
                          </div>
                      </div>
                      <div className="recipes-7-0-0-2">
                          <div className="recipes-7-0-0-2-0">
                              <div className="recipes-useful_links-0">Useful links</div>
                          </div>
                          <div className="recipes-7-0-0-2-1">
                              <div className="recipes-privacy_policy_terms_and_conditions_orders_and_tracking_return_policy_customer_care-0">
                                  <div>Privacy Policy</div>
                                  <div>Terms and Conditions</div>
                                  <div>Orders and Tracking</div>
                                  <div>Return Policy</div>
                                  <div>Customer Care</div>
                              </div>
                          </div>
                          <div className="recipes-7-0-0-2-2">
                              <div className="recipes-vector-0000031">
                                  <div className="recipes-7-0-0-2-2-0-0">
                                      <div className="recipes-vector-00000155" /> 
                                  </div>
                              </div>
                              <div className="recipes-vector-00000056">
                                  <div className="recipes-7-0-0-2-2-1-0">
                                      <div className="recipes-vector-0000042">
                                          <div className="recipes-7-0-0-2-2-1-0-0-0">
                                              <div className="recipes-vector-0000005" /> 
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="recipes-vector-0000022">
                                  <div className="recipes-7-0-0-2-2-2-0">
                                      <div className="recipes-vector-0000003" /> 
                                  </div>
                              </div>
                              <div className="recipes-vector-00000311">
                                  <div className="recipes-7-0-0-2-2-3-0">
                                      <div className="recipes-vector-0000006" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
