// Generated by greensum.pagedraw.json
import React from 'react';
import './sign_up.css';


export default class Sign_up extends React.Component {
  render() {
    return (
      <div className="sign_up-sign_up-0">
          <div className="sign_up-0">
              <div className="sign_up-home-0">Home</div>
              <div className="sign_up-shop-0">Shop</div>
              <div className="sign_up-about-0">About </div>
              <div className="sign_up-contact-0">Contact</div>
              <div className="sign_up-recipes-0">recipes</div>
              <div className="sign_up-0-5">
                  <div className="sign_up-0-5-0">
                      <div className="sign_up-vector-000">
                          <div className="sign_up-0-5-0-0-0">
                              <div className="sign_up-vector-00">
                                  <div className="sign_up-0-5-0-0-0-0-0">
                                      <div className="sign_up-vector-0" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="sign_up-_9">+91 - 9876 54321</div>
              <div className="sign_up-0-7">
                  <div className="sign_up-0-7-0">
                      <div className="sign_up-vector-00000">
                          <div className="sign_up-0-7-0-0-0">
                              <div className="sign_up-vector-0000" /> 
                          </div>
                      </div>
                  </div>
              </div>
              <div className="sign_up-search-0">Search</div>
              <div className="sign_up-0-9">
                  <div className="sign_up-0-9-0">
                      <div className="sign_up-vector-000000" /> 
                  </div>
              </div>
              <div className="sign_up-account-0">Account</div>
              <div className="sign_up-cart_0">{"Cart (0)"}</div>
          </div>
          <div className="sign_up-1">
              <div className="sign_up-rectangle_5" /> 
          </div>
          <div className="sign_up-2">
              <div className="sign_up-rectangle_3">
                  <div className="sign_up-2-0-0">
                      <div className="sign_up-login-0">Login</div>
                  </div>
              </div>
          </div>
          <div className="sign_up-3">
              <div className="sign_up-3-0">
                  <div className="sign_up-3-0-0">
                      <div className="sign_up-3-0-0-0">
                          <div className="sign_up-image-7">
                              <div className="sign_up-3-0-0-0-0-0">
                                  <div className="sign_up-lorem_ipsum-0">Lorem Ipsum</div>
                              </div>
                              <div className="sign_up-3-0-0-0-0-1">
                                  <div className="sign_up-lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_-0">
                                      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                  </div>
                              </div>
                              <div className="sign_up-3-0-0-0-0-2">
                                  <div className="sign_up-ellipse_1" /> 
                                  <div className="sign_up-ellipse_8" /> 
                                  <div className="sign_up-ellipse_9" /> 
                              </div>
                          </div>
                          <div className="sign_up-rectangle_54">
                              <div className="sign_up-3-0-0-0-1-0">
                                  <div className="sign_up-hello_d-0">{"Hello :D"}</div>
                              </div>
                              <div className="sign_up-3-0-0-0-1-1">
                                  <div className="sign_up-username-0">Username</div>
                              </div>
                              <div className="sign_up-3-0-0-0-1-2">
                                  <div className="sign_up-rectangle_38" /> 
                              </div>
                              <div className="sign_up-3-0-0-0-1-3">
                                  <div className="sign_up-email_or_phone_number-0">
                                      Email or Phone number
                                  </div>
                              </div>
                              <div className="sign_up-3-0-0-0-1-4">
                                  <div className="sign_up-rectangle_38-0" /> 
                              </div>
                              <div className="sign_up-3-0-0-0-1-5">
                                  <div className="sign_up-3-0-0-0-1-5-0">
                                      <div className="sign_up-3-0-0-0-1-5-0-0">
                                          <div className="sign_up-password-0">Password</div>
                                      </div>
                                  </div>
                                  <div className="sign_up-3-0-0-0-1-5-1">
                                      <div className="sign_up-3-0-0-0-1-5-1-0">
                                          <div className="sign_up-vector-0000004">
                                              <div className="sign_up-3-0-0-0-1-5-1-0-0-0">
                                                  <div className="sign_up-vector-0000000" /> 
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="sign_up-3-0-0-0-1-6">
                                  <div className="sign_up-rectangle_38-00" /> 
                              </div>
                              <div className="sign_up-3-0-0-0-1-7">
                                  <div className="sign_up-repeat_password-0">
                                      Repeat Password
                                  </div>
                              </div>
                              <div className="sign_up-3-0-0-0-1-8">
                                  <div className="sign_up-rectangle_38-000" /> 
                              </div>
                              <div className="sign_up-3-0-0-0-1-9">
                                  <div className="sign_up-already_have_an_account_sign_in-0">
                                      {"Already have an account ? Sign in"}
                                  </div>
                              </div>
                          </div>
                          <div className="sign_up-vector-000003" /> 
                          <div className="sign_up-vector-0000030" /> 
                          <div className="sign_up-vector-0000034" /> 
                          <div className="sign_up-vector-000002" /> 
                          <div className="sign_up-vector-0000025" /> 
                          <div className="sign_up-vector-00000045" /> 
                          <div className="sign_up-vector-0000024" /> 
                      </div>
                  </div>
              </div>
              <div className="sign_up-3-1">
                  <div className="sign_up-3-1-0">
                      <div className="sign_up-vector-000001" /> 
                  </div>
                  <div className="sign_up-3-1-1">
                      <div className="sign_up-vector-0000002" /> 
                  </div>
              </div>
              <div className="sign_up-3-2">
                  <div className="sign_up-3-2-0">
                      <div className="sign_up-3-2-0-0">
                          <div className="sign_up-vector-000004" /> 
                          <div className="sign_up-vector-0000001" /> 
                          <div className="sign_up-vector-0000029" /> 
                          <div className="sign_up-vector-0000021" /> 
                          <div className="sign_up-vector-0000011" /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="sign_up-4">
              <div className="sign_up-rectangle_6">
                  <div className="sign_up-4-0-0">
                      <div className="sign_up-4-0-0-0">
                          <div className="sign_up-4-0-0-0-0">
                              <div className="sign_up-address-0">Address</div>
                          </div>
                          <div className="sign_up-4-0-0-0-1">
                              <div className="sign_up-12">123, New Colony , Delhi</div>
                          </div>
                          <div className="sign_up-4-0-0-0-2">
                              <div className="sign_up-contact-00">Contact</div>
                          </div>
                          <div className="sign_up-4-0-0-0-3">
                              <div className="sign_up-email_greensum_gmail_com_cell_9">
                                  <div>{"Email : greensum@gmail.com"}</div>
                                  <div>{"Cell : +91 - 987654321"}</div>
                                  <div>{"Fax : greensum.io"}</div>
                              </div>
                          </div>
                      </div>
                      <div className="sign_up-4-0-0-1">
                          <div className="sign_up-4-0-0-1-0">
                              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/80c5/cd9e/9811893e3828c2a729d6f4c088384115" className="sign_up-image-9" /> 
                          </div>
                      </div>
                      <div className="sign_up-4-0-0-2">
                          <div className="sign_up-4-0-0-2-0">
                              <div className="sign_up-useful_links-0">Useful links</div>
                          </div>
                          <div className="sign_up-4-0-0-2-1">
                              <div className="sign_up-privacy_policy_terms_and_conditions_orders_and_tracking_return_policy_customer_care-0">
                                  <div>Privacy Policy</div>
                                  <div>Terms and Conditions</div>
                                  <div>Orders and Tracking</div>
                                  <div>Return Policy</div>
                                  <div>Customer Care</div>
                              </div>
                          </div>
                          <div className="sign_up-4-0-0-2-2">
                              <div className="sign_up-vector-00000305">
                                  <div className="sign_up-4-0-0-2-2-0-0">
                                      <div className="sign_up-vector-00000023" /> 
                                  </div>
                              </div>
                              <div className="sign_up-vector-0000007">
                                  <div className="sign_up-4-0-0-2-2-1-0">
                                      <div className="sign_up-vector-0000005">
                                          <div className="sign_up-4-0-0-2-2-1-0-0-0">
                                              <div className="sign_up-vector-0000009" /> 
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="sign_up-vector-0000038">
                                  <div className="sign_up-4-0-0-2-2-2-0">
                                      <div className="sign_up-vector-0000008" /> 
                                  </div>
                              </div>
                              <div className="sign_up-vector-00000097">
                                  <div className="sign_up-4-0-0-2-2-3-0">
                                      <div className="sign_up-vector-0000032" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
